#pragma once
#define SFML_NO_DEPRECATED_WARNINGS
#include <TGUI/TGUI.hpp>
#include <iostream>
#include <iomanip>
#include <stdio.h>
#include<stdlib.h>
#include <vector>
#include <map>
#include <string>
#include <sstream>
#include "parameters.h"

using namespace std;



class User_Input {

private:
	int status_bar_width = 300;
	void poll_events(sf::RenderWindow & wind);

	vector <bool> one_shot_switch;
	vector <bool> momentary_switch;
	vector <bool> toggle_switch;
	vector <float> values_switch;




	bool momentary_switch_key[100] = { 0 };
	bool one_shot_switch_key[100] = { 0 };
	bool toggle_switch_key[100] = { 0 };



	int mouse_wheel_delta = 0;
	bool resize_needed = 0;
	bool close_window_needed = 0;
	int screen_width_after_resize;
	int screen_height_after_resize;


	tgui::Gui gui;


	void pollLinkedTabs();
	stringstream form_file;
	
public:
	void adjustVariableSizeIcons(sf::RenderWindow& wind);

		//Stuff for New Lab Update
		void set_sorter_panel_visibility(bool x){ gui.get<tgui::Panel>("cellSorter_Panel")->setVisible(x);	}
		void set_monitor_panel_visibility(bool x) { gui.get<tgui::Panel>("cellRules_Panel")->setVisible(x); }
		void set_iterate_panel_visibility(bool x) { gui.get<tgui::Panel>("_iteratePanel")->setVisible(x); }
		void set_field_panel_visibility(bool x) { gui.get<tgui::Panel>("Field_Panel")->setVisible(x);}
		void set_manipulate_panel_visibility(bool x) { gui.get<tgui::Panel>("manipulate_panel")->setVisible(x); }
		void set_editor_panel_visibility(bool x) { gui.get<tgui::Panel>("Editor_Panel")->setVisible(x); gui.get<tgui::ChildWindow>("_ed_ChildWindow")->setVisible(x);}
		void set_debug_textbox_visibility(bool x) {  gui.get<tgui::TextBox>("_debug_textbox")->setVisible(x); gui.get<tgui::TextBox>("rule_viewer")->setVisible(x);	}
		void set_text_to_mini_rule_viewer(string s) { gui.get<tgui::TextBox>("rule_viewer")->setText(s); }

		void set_wish_to_save_visibility(bool x) { gui.get<tgui::ChildWindow>("_wts_ChildWindow")->setVisible(x); gui.get<tgui::ChildWindow>("_wts_ChildWindow")->moveToFront();}
	
		void set_syntax_guide_visibility(bool x){ gui.get<tgui::TextBox>("_ed_syntaxTextBox")->setVisible(x); }
		void set_wts_filename_label(string s) { gui.get<tgui::Label>("_wts_filename")->setText(s); }
		void set_save_childwindow_visibility(bool x) { gui.get<tgui::ChildWindow>("_sd_ChildWindow")->setVisible(x); gui.get<tgui::ChildWindow>("_sd_ChildWindow")->moveToFront();}
		bool is_save_childwindow_visible() { return  gui.get<tgui::ChildWindow>("_sd_ChildWindow")->isVisible();}
		void set_load_childwindow_visibility(bool x) {
			gui.get<tgui::ChildWindow>("_ld_ChildWindow")->setVisible(x); gui.get<tgui::ChildWindow>("_ld_ChildWindow")->moveToFront();	}
		bool is_load_childwindow_visible() { return  gui.get<tgui::ChildWindow>("_ld_ChildWindow")->isVisible(); }
		void turn_on_load_dialog2(sf::RenderWindow& wind, int file_type_flag);
		void turn_on_wts_dialog2(sf::RenderWindow& wind);
		void turn_on_save_dialog2(sf::RenderWindow& wind, string proposed_file_name);

		void set_Iterate_To_Step() {
			gui.get<tgui::RadioButton>("_it_step_RadioButton")->setChecked(1);
		}
		bool isDebugTextBoxVisible() {
			return  gui.get<tgui::TextBox>("_debug_textbox")->isVisible();
		}
		void setDebugCheckBox(bool x) {
			gui.get<tgui::CheckBox>("_cr_debugcheckbox")->setChecked(x);
	}
	

	string getRuleText() {
		return gui.get<tgui::TextBox>("_ed_TextBox")->getText();
	}

	int getOrientationKnob() { return gui.get<tgui::Knob>("field_knob")->getValue(); };
	void uncheckManualPlacementCheckbox() { gui.get<tgui::CheckBox>("cr_manualPlacement_Checkbox")->setChecked(0); };
	void setIteratePanelRuleLoadedLabel(string s);
	void setIteratePanelFieldLoadedLabel(string s);
	void setTimeLabel(float a, float b);
	void setUnsavedEditorLabel(bool x) {
		if (x) { gui.get<tgui::Label>("_ed_unsaved")->setVisible(1); }
		else {
			gui.get<tgui::Label>("_ed_unsaved")->setVisible(0);
		}
	}
	void setEditorFileNameLabel(string fn) {
		gui.get<tgui::Label>("_ed_filenameLabel")->setText(fn);
	}

	void load_state_names_to_GUI(vector <string> s);
	string get_selected_state_name_from_combo_box() {return  gui.get<tgui::ComboBox>("cr_ManualPlacementComboBox")->getSelectedItem();}

	
	void setEditorTextAndLabels(string s, string file);

	void turn_off_load_dialog();
	void turn_off_save_dialog();
	void turn_off_edit_dialog();
	void turn_off_wts_dialog();

	bool shouldUseNormalCursor() {

		if (gui.get<tgui::ChildWindow>("_ld_ChildWindow")->isVisible() ||
			gui.get<tgui::ChildWindow>("_ed_ChildWindow")->isVisible() ||
			gui.get<tgui::ChildWindow>("_sd_ChildWindow")->isVisible() ||
			gui.get<tgui::ChildWindow>("_wts_ChildWindow")->isVisible()) {
			return 1;
		}
		return 0;
	}

	void setTextToMonitorTextBox(string s) {
		gui.get<tgui::TextBox>("monitor_textbox")->setText(s);
	}
	void addTextToDebugTextBox(string s) {
		gui.get<tgui::TextBox>("_debug_textbox")->addText(s);
	}
	void clearTextFromDebugTextBox() {
		gui.get<tgui::TextBox>("_debug_textbox")->setText("");
	}
	void clearAndLoadEditBoxErrorText(string s);
	string getLoadDialogFileName();
	string getSaveDialogFileName();
	void displayLoadDialogErrorLabel();
	void displaySaveDialogErrorLabel();
	

	void adjustSaveLoadLabelsForFileType(int x);

	void create_widgets(sf::RenderWindow & wind);
	void create_button_widget_helper(string s, int n);
	void create_slider_widget_helper(string s, string label, string label_text, int precision);
	sf::Vector2f getMouseWorldPosition( sf::RenderWindow & wind, const sf::View & view);
	sf::Vector2i getMouseRawPosition(sf::RenderWindow & wind);
	void poll(sf::RenderWindow & wind);
	int getGUI_FIELD_VALUE_SWATCH();
	bool getGUI_ITERATE_BUTTON();
	void setStateNamestoComboBox(vector <string> sn);
	bool getGUI_Momentary(int x) { return momentary_switch[x]; }
	bool getGUI_One_Shot(int x) { return one_shot_switch[x]; }
	bool getGUI_Toggle(int x) { return toggle_switch[x]; }
	bool getKeyboard_Momentary_switch(enum sf::Keyboard::Key x) { return momentary_switch_key[x]; }
	bool getKeyboard_One_shot_switch(enum sf::Keyboard::Key x) { return one_shot_switch_key[x]; }
	bool getKeyboard_Toggle_switch(enum sf::Keyboard::Key x) { return toggle_switch_key[x]; }
	bool shouldMouseBeAbleToDrawOrPlaceCells();
	bool isMouseOnLargerWidgets();
	int getMouseWheelDelta() { return mouse_wheel_delta; }
	bool isResizeNeeded() { return resize_needed; }
	bool isCloseWindowNeeded() { return close_window_needed; }
	void drawGUI(sf::View v) { gui.setView(v);  gui.draw(); }
	void setFont(sf::Font f) { gui.setFont(f); }
	void loadSwitchData(vector <bool>& one_shot, vector <bool>& momentary, vector <bool>& toggle, vector <float>& values);
	User_Input() {
		//gui.setFont("consola.ttf");
		one_shot_switch = vector <bool> (gui_LAST_ENTRY+1,0);
		momentary_switch = vector <bool>(gui_LAST_ENTRY +1, 0);
		toggle_switch = vector <bool>(gui_LAST_ENTRY + 1, 0);
		values_switch = vector <float>(gui_LAST_ENTRY + 1, 0);
		create_syntax_guide();
		create_form_stream();
	}
	
	string syntax;
	void create_syntax_guide() {

		vector<string> syntax_holder;
		syntax_holder.clear();
		syntax_holder.push_back("LV = literal value\n");
		syntax_holder.push_back("UV = U_VAR\n");
		syntax_holder.push_back("VV = V_VAR\n");
		syntax_holder.push_back("GV = G_VAR\n");
		syntax_holder.push_back("IV = Internal Variable\n");
		syntax_holder.push_back("IV-RAM = writeable IV\n");
		syntax_holder.push_back("SN = state name\n");
		syntax_holder.push_back("FN = Field No.\n");
		syntax_holder.push_back("\n");
		syntax_holder.push_back("************\n");
		syntax_holder.push_back("CONDITIONS:\n");
		syntax_holder.push_back("************\n");
		syntax_holder.push_back("\n");
		syntax_holder.push_back("ENTERING_STATE\n");
		syntax_holder.push_back("\n");
		syntax_holder.push_back("POISSON[a]\n");
		syntax_holder.push_back("  a: LV\n");
		syntax_holder.push_back("\n");
		syntax_holder.push_back("ADJ_CELLS{a}[b,c]\n");
		syntax_holder.push_back("  a: SN (optional)\n");
		syntax_holder.push_back("  b, c (optional): LV,UV,GV,IV\n");
		syntax_holder.push_back("\n");
		syntax_holder.push_back("ADJ_MEMBRANES{a}[b,c]\n");
		syntax_holder.push_back("  a: SN (optional)\n");
		syntax_holder.push_back("  b, c (optional): LV,UV,GV,IV\n");
		syntax_holder.push_back("\n");
		syntax_holder.push_back("ADJ_MEMBRANES_PERCENT{a}[b,c]\n");
		syntax_holder.push_back("  a: SN\n");
		syntax_holder.push_back("  b, c (optional): LV,UV,GV,IV\n");
		syntax_holder.push_back("\n");
		syntax_holder.push_back("FIELD[a,b]\n");
		syntax_holder.push_back("  a, b (optional): FN\n");
		syntax_holder.push_back("\n");
		syntax_holder.push_back("FIELD_EDGES{a}[a,b]\n");
		syntax_holder.push_back("  a: FN\n");
		syntax_holder.push_back("  a, b (optional): LB\n");
		syntax_holder.push_back("\n");
		syntax_holder.push_back("************\n");
		syntax_holder.push_back("COMMANDS:\n");
		syntax_holder.push_back("************\n");
		syntax_holder.push_back("MITOSIS\n");
		syntax_holder.push_back("\n");
		syntax_holder.push_back("MITOSIS{a}\n");
		syntax_holder.push_back("   a: SN [daughter state]\n");
		syntax_holder.push_back("\n");
		syntax_holder.push_back("MITOSIS[a,b]\n");
		syntax_holder.push_back("   a: VV [cleavage]\n");
		syntax_holder.push_back("   b (optional): LV,UV,IV [rot. offset]\n");
		syntax_holder.push_back("   \n");
		syntax_holder.push_back("MITOSIS{a}[b,c,d]\n");
		syntax_holder.push_back("   a: SN  [daughter state]\n");
		syntax_holder.push_back("   b: VV  [cleavage]\n");
		syntax_holder.push_back("   c (optional): LV,UV,IV [rot. offset]\n");
		syntax_holder.push_back("   d (optional): \"CW\" or \"CCW\"\n");
		syntax_holder.push_back("\n");
		syntax_holder.push_back("SET_RAND{a}[b, c]\n");
		syntax_holder.push_back("       a: UV,IV-RAM\n");
		syntax_holder.push_back("       b,c: UV,IV,GV,LV\n");
		syntax_holder.push_back("\n");
		syntax_holder.push_back("FIELD_ACTIVE[a]\n");
		syntax_holder.push_back("    a: 1 or 0\n");
		syntax_holder.push_back("\n");
		syntax_holder.push_back("MIGRATE[a,b,c]\n");
		syntax_holder.push_back("       a: VV\n");
		syntax_holder.push_back("       b: UV,IV,LV [force]\n");
		syntax_holder.push_back("       c (optional): LV,UV [rot. offset]\n");
		syntax_holder.push_back("\n");
		syntax_holder.push_back("RGB(a,b,c)\n");
		syntax_holder.push_back("       a,b,c: UV,GV,IV\n");
		syntax_holder.push_back("\n");
		syntax_holder.push_back("DIE\n");
		syntax_holder.push_back("\n");
		syntax_holder.push_back("END\n");
		syntax_holder.push_back("\n");
		syntax_holder.push_back("SET_VEC{a}[b]\n");
		syntax_holder.push_back("   a: VV\n");
		syntax_holder.push_back("   b: SN,UV,GV\n");
		syntax_holder.push_back("\n");
		syntax_holder.push_back("SET_VEC{a}[b,c]\n");
		syntax_holder.push_back("   a: VV\n");
		syntax_holder.push_back("   b,c: LV\n");
		syntax_holder.push_back("\n");
		syntax_holder.push_back("MOD_PP_LOCATION[a,b,c]\n");
		syntax_holder.push_back("   a: VV\n");
		syntax_holder.push_back("   b: LV [amount of translation]\n");
		syntax_holder.push_back("   c: LV,UV [rot. offset]\n");
		syntax_holder.push_back("\n");
		syntax_holder.push_back("ADJUST_PP_SCALE[a]\n");
		syntax_holder.push_back("   a: LV\n");
		syntax_holder.push_back("\n");
		syntax_holder.push_back("************\n");
		syntax_holder.push_back("GAP_JUNCTIONS:\n");
		syntax_holder.push_back("************\n");
		syntax_holder.push_back("<a,b,c>(d)\n");
		syntax_holder.push_back("   a,b: SN\n");
		syntax_holder.push_back("   c: UV\n");
		syntax_holder.push_back("   d: LV\n");
		syntax_holder.push_back("\n");
		syntax_holder.push_back("************\n");
		syntax_holder.push_back("ADHESIONS:\n");
		syntax_holder.push_back("************\n");
		syntax_holder.push_back("<a,b>(c)\n");
		syntax_holder.push_back("   a,b: SN or \"SELF\"\n");
		syntax_holder.push_back("   c: LV\n");
		syntax_holder.push_back("\n");
		syntax_holder.push_back("DEFAULT ADHESIONS:\n");
		syntax_holder.push_back("a<->a: -6.5\n");
		syntax_holder.push_back("a<->b: 4.0\n");
		syntax_holder.push_back("a<->SELF: -20.0\n");
		syntax_holder.push_back("a<->MEDIUM: 2.4\n");
		stringstream result;
		for (int x = 0; x < syntax_holder.size(); x++) {
			result << syntax_holder[x];
		}

		syntax = result.str();

	}

	void create_form_stream() {
		vector <string> form_holder;
		form_holder.clear();
		form_holder.push_back("Renderer.1 {\n");
		form_holder.push_back("    textcolor = rgb(190, 190, 190);\n");
		form_holder.push_back("    textcolorhover = rgb(250, 250, 250);\n");
		form_holder.push_back("    texturechecked = \"icons.png\" Part(124, 32, 32, 32);\n");
		form_holder.push_back("    texturecheckeddisabled = None;\n");
		form_holder.push_back("    texturecheckedfocused = \"icons.png\" Part(252, 32, 32, 32);\n");
		form_holder.push_back("    texturecheckedhover = \"icons.png\" Part(188, 32, 32, 32);\n");
		form_holder.push_back("    textureunchecked = \"icons.png\" Part(92, 32, 32, 32);\n");
		form_holder.push_back("    textureuncheckeddisabled = None;\n");
		form_holder.push_back("    textureuncheckedfocused = \"icons.png\" Part(220, 32, 32, 32);\n");
		form_holder.push_back("    textureuncheckedhover = \"icons.png\" Part(156, 32, 32, 32);\n");
		form_holder.push_back("}\n");
		form_holder.push_back("\n");
		form_holder.push_back("Renderer.2 {\n");
		form_holder.push_back("    texturethumb = \"icons.png\" Part(243, 150, 30, 30);\n");
		form_holder.push_back("    texturethumbhover = None;\n");
		form_holder.push_back("    texturetrack = \"icons.png\" Part(203, 150, 20, 45) Middle(0, 15, 20, 15);\n");
		form_holder.push_back("    texturetrackhover = \"icons.png\" Part(223, 150, 20, 45) Middle(0, 15, 20, 15);\n");
		form_holder.push_back("}\n");
		form_holder.push_back("\n");
		form_holder.push_back("Renderer.3 {\n");
		form_holder.push_back("    textcolor = rgb(190, 190, 190);\n");
		form_holder.push_back("    textcolorhover = rgb(250, 250, 250);\n");
		form_holder.push_back("    texturechecked = \"icons.png\" Part(124, 0, 32, 32);\n");
		form_holder.push_back("    texturecheckeddisabled = None;\n");
		form_holder.push_back("    texturecheckedfocused = \"icons.png\" Part(252, 0, 32, 32);\n");
		form_holder.push_back("    texturecheckedhover = \"icons.png\" Part(188, 0, 32, 32);\n");
		form_holder.push_back("    textureunchecked = \"icons.png\" Part(92, 0, 32, 32);\n");
		form_holder.push_back("    textureuncheckeddisabled = None;\n");
		form_holder.push_back("    textureuncheckedfocused = \"icons.png\" Part(220, 0, 32, 32);\n");
		form_holder.push_back("    textureuncheckedhover = \"icons.png\" Part(156, 0, 32, 32);\n");
		form_holder.push_back("}\n");
		form_holder.push_back("\n");
		form_holder.push_back("Renderer.4 {\n");
		form_holder.push_back("    distancetoside = 8;\n");
		form_holder.push_back("    selectedtextcolor = White;\n");
		form_holder.push_back("    textcolor = rgb(190, 190, 190);\n");
		form_holder.push_back("    texturedisabledtab = None;\n");
		form_holder.push_back("    textureselectedtab = \"icons.png\" Part(0, 32, 60, 32) Middle(16, 0, 28, 32);\n");
		form_holder.push_back("    textureselectedtabhover = None;\n");
		form_holder.push_back("    texturetab = \"icons.png\" Part(0, 0, 60, 32) Middle(16, 0, 28, 32);\n");
		form_holder.push_back("    texturetabhover = None;\n");
		form_holder.push_back("}\n");
		form_holder.push_back("\n");
		form_holder.push_back("Renderer.5 {\n");
		form_holder.push_back("    backgroundcolor = rgb( 80, 80, 80);\n");
		form_holder.push_back("    bordercolor = Black;\n");
		form_holder.push_back("    borders = (1, 1, 1, 1);\n");
		form_holder.push_back("    distancetoside = 5;\n");
		form_holder.push_back("    maximizebutton = {\n");
		form_holder.push_back("texture = \"icons.png\" Part(48, 194, 15, 15);\n");
		form_holder.push_back("texturedown = \"icons.png\" Part(78, 194, 15, 15);\n");
		form_holder.push_back("texturehover = \"icons.png\" Part(63, 194, 15, 15);\n");
		form_holder.push_back("};\n");
		form_holder.push_back("    minimizebutton = {\n");
		form_holder.push_back("texture = \"icons.png\" Part(93, 194, 15, 15);\n");
		form_holder.push_back("texturedown = \"icons.png\" Part(123, 194, 15, 15);\n");
		form_holder.push_back("texturehover = \"icons.png\" Part(108, 194, 15, 15);\n");
		form_holder.push_back("};\n");
		form_holder.push_back("    paddingbetweenbuttons = 2;\n");
		form_holder.push_back("    showtextontitlebuttons = false;\n");
		form_holder.push_back("    texturebackground = None;\n");
		form_holder.push_back("    texturetitlebar = \"icons.png\" Part(48, 154, 75, 25) Middle(25, 0, 25, 25);\n");
		form_holder.push_back("    titlecolor = rgb(190, 190, 190);\n");
		form_holder.push_back("\n");
		form_holder.push_back("    closebutton {\n");
		form_holder.push_back("        texture = \"icons.png\" Part(48, 179, 15, 15);\n");
		form_holder.push_back("        texturedown = \"icons.png\" Part(78, 179, 15, 15);\n");
		form_holder.push_back("        texturehover = \"icons.png\" Part(63, 179, 15, 15);\n");
		form_holder.push_back("    }\n");
		form_holder.push_back("}\n");
		form_holder.push_back("\n");
		form_holder.push_back("Renderer.6 {\n");
		form_holder.push_back("    caretcolor = rgb(110, 110, 255);\n");
		form_holder.push_back("    defaulttextcolor = rgb(120, 120, 120);\n");
		form_holder.push_back("    padding = (6, 4, 6, 4);\n");
		form_holder.push_back("    selectedtextbackgroundcolor = rgb( 10, 110, 255);\n");
		form_holder.push_back("    selectedtextcolor = White;\n");
		form_holder.push_back("    textcolor = rgb(190, 190, 190);\n");
		form_holder.push_back("    texture = \"icons.png\" Part(0, 114, 60, 40) Middle(15, 0, 30, 40);\n");
		form_holder.push_back("    texturedisabled = None;\n");
		form_holder.push_back("    texturefocused = \"icons.png\" Part(120, 114, 60, 40) Middle(15, 0, 30, 40);\n");
		form_holder.push_back("    texturehover = \"icons.png\" Part(60, 114, 60, 40) Middle(15, 0, 30, 40);\n");
		form_holder.push_back("}\n");
		form_holder.push_back("\n");
		form_holder.push_back("Renderer.7 {\n");
		form_holder.push_back("    textcolor = rgb(190, 190, 190);\n");
		form_holder.push_back("    texturebackground = None;\n");
		form_holder.push_back("\n");
		form_holder.push_back("    scrollbar {\n");
		form_holder.push_back("        texturearrowdown = \"icons.png\" Part(163, 174, 20, 20) Middle(0, 1, 20, 19);\n");
		form_holder.push_back("        texturearrowdownhover = \"icons.png\" Part(183, 174, 20, 20) Middle(0, 1, 20, 19);\n");
		form_holder.push_back("        texturearrowup = \"icons.png\" Part(163, 154, 20, 20) Middle(0, 0, 20, 19);\n");
		form_holder.push_back("        texturearrowuphover = \"icons.png\" Part(183, 154, 20, 20) Middle(0, 0, 20, 19);\n");
		form_holder.push_back("        texturethumb = \"icons.png\" Part(143, 154, 20, 20);\n");
		form_holder.push_back("        texturethumbhover = \"icons.png\" Part(143, 174, 20, 20);\n");
		form_holder.push_back("        texturetrack = \"icons.png\" Part(123, 154, 20, 20);\n");
		form_holder.push_back("        texturetrackhover = \"icons.png\" Part(123, 174, 20, 20);\n");
		form_holder.push_back("    }\n");
		form_holder.push_back("}\n");
		form_holder.push_back("\n");
		form_holder.push_back("Renderer.8 {\n");
		form_holder.push_back("    textcolor = rgb(190, 190, 190);\n");
		form_holder.push_back("    textcolorhover = rgb(250, 250, 250);\n");
		form_holder.push_back("    texture = \"icons.png\" Part( 0, 64, 45, 50) Middle(10, 0, 25, 50);\n");
		form_holder.push_back("    texturedisabled = None;\n");
		form_holder.push_back("    texturedown = \"icons.png\" Part(90, 64, 45, 50) Middle(10, 0, 25, 50);\n");
		form_holder.push_back("    texturefocused = \"icons.png\" Part(135, 64, 45, 50) Middle(10, 0, 25, 50);\n");
		form_holder.push_back("    texturehover = \"icons.png\" Part(45, 64, 45, 50) Middle(10, 0, 25, 50);\n");
		form_holder.push_back("}\n");
		form_holder.push_back("\n");
		form_holder.push_back("Renderer.9 {\n");
		form_holder.push_back("    backgroundcolor = rgb(80, 80, 80);\n");
		form_holder.push_back("    texturebackground = None;\n");
		form_holder.push_back("}\n");
		form_holder.push_back("\n");
		form_holder.push_back("Renderer.10 {\n");
		form_holder.push_back("    caretcolor = rgb(110, 110, 255);\n");
		form_holder.push_back("    padding = (3, 3, 3, 3);\n");
		form_holder.push_back("    selectedtextbackgroundcolor = rgb( 10, 110, 255);\n");
		form_holder.push_back("    selectedtextcolor = White;\n");
		form_holder.push_back("    textcolor = rgb(190, 255, 190);\n");
		form_holder.push_back("    texturebackground = \"icons.png\" Part(0, 154, 48, 48) Middle(16, 16, 16, 16);\n");
		form_holder.push_back("\n");
		form_holder.push_back("    scrollbar {\n");
		form_holder.push_back("        texturearrowdown = \"icons.png\" Part(163, 174, 20, 20) Middle(0, 1, 20, 19);\n");
		form_holder.push_back("        texturearrowdownhover = \"icons.png\" Part(183, 174, 20, 20) Middle(0, 1, 20, 19);\n");
		form_holder.push_back("        texturearrowup = \"icons.png\" Part(163, 154, 20, 20) Middle(0, 0, 20, 19);\n");
		form_holder.push_back("        texturearrowuphover = \"icons.png\" Part(183, 154, 20, 20) Middle(0, 0, 20, 19);\n");
		form_holder.push_back("        texturethumb = \"icons.png\" Part(143, 154, 20, 20);\n");
		form_holder.push_back("        texturethumbhover = \"icons.png\" Part(143, 174, 20, 20);\n");
		form_holder.push_back("        texturetrack = \"icons.png\" Part(123, 154, 20, 20);\n");
		form_holder.push_back("        texturetrackhover = \"icons.png\" Part(123, 174, 20, 20);\n");
		form_holder.push_back("    }\n");
		form_holder.push_back("}\n");
		form_holder.push_back("\n");
		form_holder.push_back("Panel._iteratePanel {\n");
		form_holder.push_back("    Position = (4, 60);\n");
		form_holder.push_back("    Size = (292, 220);\n");
		form_holder.push_back("    renderer = &9;\n");
		form_holder.push_back("\n");
		form_holder.push_back("    Button._it_iterateButton {\n");
		form_holder.push_back("        Position = (10, 70);\n");
		form_holder.push_back("        Size = (60, 30);\n");
		form_holder.push_back("        Text = Iterate;\n");
		form_holder.push_back("        TextSize = 13;\n");
		form_holder.push_back("        renderer = &8;\n");
		form_holder.push_back("    }\n");
		form_holder.push_back("\n");
		form_holder.push_back("    RadioButton._it_step_RadioButton {\n");
		form_holder.push_back("        Position = (80, 55);\n");
		form_holder.push_back("        Size = (18, 18);\n");
		form_holder.push_back("        Text = Step;\n");
		form_holder.push_back("        TextSize = 10;\n");
		form_holder.push_back("        renderer = &1;\n");
		form_holder.push_back("    }\n");
		form_holder.push_back("\n");
		form_holder.push_back("    RadioButton._it_momentary_RadioButton {\n");
		form_holder.push_back("        Position = (80, 75);\n");
		form_holder.push_back("        Size = (18, 18);\n");
		form_holder.push_back("        Text = Momentary;\n");
		form_holder.push_back("        TextSize = 10;\n");
		form_holder.push_back("        renderer = &1;\n");
		form_holder.push_back("    }\n");
		form_holder.push_back("\n");
		form_holder.push_back("    RadioButton._it_toggle_RadioButton {\n");
		form_holder.push_back("        Position = (80, 95);\n");
		form_holder.push_back("        Size = (18, 18);\n");
		form_holder.push_back("        Text = Toggle;\n");
		form_holder.push_back("        TextSize = 10;\n");
		form_holder.push_back("        renderer = &1;\n");
		form_holder.push_back("    }\n");
		form_holder.push_back("\n");
		form_holder.push_back("    Slider._it_speed_Slider {\n");
		form_holder.push_back("        ChangeValueOnScroll = true;\n");
		form_holder.push_back("        InvertedDirection = false;\n");
		form_holder.push_back("        Maximum = 12;\n");
		form_holder.push_back("        Minimum = 1;\n");
		form_holder.push_back("        Position = (20, 130);\n");
		form_holder.push_back("        Size = (110, 10);\n");
		form_holder.push_back("        Step = 1;\n");
		form_holder.push_back("        Value = 1;\n");
		form_holder.push_back("        renderer = &2;\n");
		form_holder.push_back("    }\n");
		form_holder.push_back("\n");
		form_holder.push_back("    Label._it_speed_Label {\n");
		form_holder.push_back("        IgnoreMouseEvents = true;\n");
		form_holder.push_back("        Position = (20, 111);\n");
		form_holder.push_back("        ScrollbarPolicy = Never;\n");
		form_holder.push_back("        Size = (107.2, 18);\n");
		form_holder.push_back("        Text = Speed;\n");
		form_holder.push_back("        TextSize = 10;\n");
		form_holder.push_back("        renderer = &7;\n");
		form_holder.push_back("    }\n");
		form_holder.push_back("\n");
		form_holder.push_back("    Slider._it_flux_Slider {\n");
		form_holder.push_back("        ChangeValueOnScroll = true;\n");
		form_holder.push_back("        InvertedDirection = false;\n");
		form_holder.push_back("        Maximum = 35;\n");
		form_holder.push_back("        Minimum = 1;\n");
		form_holder.push_back("        Position = (20, 168);\n");
		form_holder.push_back("        Size = (220, 10);\n");
		form_holder.push_back("        Step = 0.25;\n");
		form_holder.push_back("        Value = 10;\n");
		form_holder.push_back("        renderer = &2;\n");
		form_holder.push_back("    }\n");
		form_holder.push_back("\n");
		form_holder.push_back("    Label._it_flux_Label {\n");
		form_holder.push_back("        IgnoreMouseEvents = true;\n");
		form_holder.push_back("        Position = (20, 152);\n");
		form_holder.push_back("        ScrollbarPolicy = Never;\n");
		form_holder.push_back("        Size = (147.2, 18);\n");
		form_holder.push_back("        Text = \"Membrane Flux\";\n");
		form_holder.push_back("        TextSize = 10;\n");
		form_holder.push_back("        renderer = &7;\n");
		form_holder.push_back("    }\n");
		form_holder.push_back("\n");
		form_holder.push_back("    Label._it_rule_loaded_label {\n");
		form_holder.push_back("        Position = (20, 185);\n");
		form_holder.push_back("        ScrollbarPolicy = Never;\n");
		form_holder.push_back("        Size = (250, 18);\n");
		form_holder.push_back("        Text = \"Rules in CPU:\";\n");
		form_holder.push_back("        TextSize = 10;\n");
		form_holder.push_back("\n");
		form_holder.push_back("        Renderer {\n");
		form_holder.push_back("            textcolor = #A8FF82;\n");
		form_holder.push_back("            texturebackground = None;\n");
		form_holder.push_back("\n");
		form_holder.push_back("            scrollbar {\n");
		form_holder.push_back("                texturearrowdown = \"icons.png\" Part(163, 174, 20, 20) Middle(0, 1, 20, 19);\n");
		form_holder.push_back("                texturearrowdownhover = \"icons.png\" Part(183, 174, 20, 20) Middle(0, 1, 20, 19);\n");
		form_holder.push_back("                texturearrowup = \"icons.png\" Part(163, 154, 20, 20) Middle(0, 0, 20, 19);\n");
		form_holder.push_back("                texturearrowuphover = \"icons.png\" Part(183, 154, 20, 20) Middle(0, 0, 20, 19);\n");
		form_holder.push_back("                texturethumb = \"icons.png\" Part(143, 154, 20, 20);\n");
		form_holder.push_back("                texturethumbhover = \"icons.png\" Part(143, 174, 20, 20);\n");
		form_holder.push_back("                texturetrack = \"icons.png\" Part(123, 154, 20, 20);\n");
		form_holder.push_back("                texturetrackhover = \"icons.png\" Part(123, 174, 20, 20);\n");
		form_holder.push_back("            }\n");
		form_holder.push_back("        }\n");
		form_holder.push_back("    }\n");
		form_holder.push_back("\n");
		form_holder.push_back("    Button._it_clear {\n");
		form_holder.push_back("        Position = (10, 10);\n");
		form_holder.push_back("        Size = (60, 30);\n");
		form_holder.push_back("        Text = Clear;\n");
		form_holder.push_back("        TextSize = 13;\n");
		form_holder.push_back("        renderer = &8;\n");
		form_holder.push_back("    }\n");
		form_holder.push_back("\n");
		form_holder.push_back("    CheckBox._it_drawGradient {\n");
		form_holder.push_back("        Position = (180, 72);\n");
		form_holder.push_back("        Size = (18, 18);\n");
		form_holder.push_back("        Text = \"Draw Gradients\";\n");
		form_holder.push_back("        TextSize = 10;\n");
		form_holder.push_back("        renderer = &3;\n");
		form_holder.push_back("    }\n");
		form_holder.push_back("\n");
		form_holder.push_back("    CheckBox._it_drawField {\n");
		form_holder.push_back("        Position = (190, 120);\n");
		form_holder.push_back("        Size = (18, 18);\n");
		form_holder.push_back("        Text = \"Draw Field\";\n");
		form_holder.push_back("        TextSize = 10;\n");
		form_holder.push_back("        renderer = &3;\n");
		form_holder.push_back("    }\n");
		form_holder.push_back("\n");
		form_holder.push_back("    CheckBox._it_drawOrientations {\n");
		form_holder.push_back("        Position = (190, 144);\n");
		form_holder.push_back("        Size = (18, 18);\n");
		form_holder.push_back("        Text = \"Draw Orient.\";\n");
		form_holder.push_back("        TextSize = 10;\n");
		form_holder.push_back("        renderer = &3;\n");
		form_holder.push_back("    }\n");
		form_holder.push_back("\n");
		form_holder.push_back("    Label._it_Field_in_memory {\n");
		form_holder.push_back("        Position = (20, 205);\n");
		form_holder.push_back("        ScrollbarPolicy = Never;\n");
		form_holder.push_back("        Size = (250, 18);\n");
		form_holder.push_back("        Text = \"Field in CPU:  NONE\";\n");
		form_holder.push_back("        TextSize = 10;\n");
		form_holder.push_back("\n");
		form_holder.push_back("        Renderer {\n");
		form_holder.push_back("            textcolor = #A8FF82;\n");
		form_holder.push_back("            texturebackground = None;\n");
		form_holder.push_back("\n");
		form_holder.push_back("            scrollbar {\n");
		form_holder.push_back("                texturearrowdown = \"icons.png\" Part(163, 174, 20, 20) Middle(0, 1, 20, 19);\n");
		form_holder.push_back("                texturearrowdownhover = \"icons.png\" Part(183, 174, 20, 20) Middle(0, 1, 20, 19);\n");
		form_holder.push_back("                texturearrowup = \"icons.png\" Part(163, 154, 20, 20) Middle(0, 0, 20, 19);\n");
		form_holder.push_back("                texturearrowuphover = \"icons.png\" Part(183, 154, 20, 20) Middle(0, 0, 20, 19);\n");
		form_holder.push_back("                texturethumb = \"icons.png\" Part(143, 154, 20, 20);\n");
		form_holder.push_back("                texturethumbhover = \"icons.png\" Part(143, 174, 20, 20);\n");
		form_holder.push_back("                texturetrack = \"icons.png\" Part(123, 154, 20, 20);\n");
		form_holder.push_back("                texturetrackhover = \"icons.png\" Part(123, 174, 20, 20);\n");
		form_holder.push_back("            }\n");
		form_holder.push_back("        }\n");
		form_holder.push_back("    }\n");
		form_holder.push_back("\n");
		form_holder.push_back("    CheckBox._it_useField {\n");
		form_holder.push_back("        Position = (180, 96);\n");
		form_holder.push_back("        Size = (18, 18);\n");
		form_holder.push_back("        Text = \"Use Field\";\n");
		form_holder.push_back("        TextSize = 10;\n");
		form_holder.push_back("        renderer = &3;\n");
		form_holder.push_back("    }\n");
		form_holder.push_back("\n");
		form_holder.push_back("    CheckBox.IT_fancy_checkbox {\n");
		form_holder.push_back("        Position = (180, 24);\n");
		form_holder.push_back("        Size = (18, 18);\n");
		form_holder.push_back("        Text = \"Fancy Graphics\";\n");
		form_holder.push_back("        TextSize = 10;\n");
		form_holder.push_back("        renderer = &3;\n");
		form_holder.push_back("    }\n");
		form_holder.push_back("\n");
		form_holder.push_back("    Label.Label1 {\n");
		form_holder.push_back("        Position = (100, 10);\n");
		form_holder.push_back("        ScrollbarPolicy = Never;\n");
		form_holder.push_back("        Size = (177.2, 32.5161);\n");
		form_holder.push_back("        Text = Label;\n");
		form_holder.push_back("        TextSize = 13;\n");
		form_holder.push_back("        Visible = false;\n");
		form_holder.push_back("\n");
		form_holder.push_back("        Renderer {\n");
		form_holder.push_back("            textcolor = #FF8C8C;\n");
		form_holder.push_back("            texturebackground = None;\n");
		form_holder.push_back("\n");
		form_holder.push_back("            scrollbar {\n");
		form_holder.push_back("                texturearrowdown = \"icons.png\" Part(163, 174, 20, 20) Middle(0, 1, 20, 19);\n");
		form_holder.push_back("                texturearrowdownhover = \"icons.png\" Part(183, 174, 20, 20) Middle(0, 1, 20, 19);\n");
		form_holder.push_back("                texturearrowup = \"icons.png\" Part(163, 154, 20, 20) Middle(0, 0, 20, 19);\n");
		form_holder.push_back("                texturearrowuphover = \"icons.png\" Part(183, 154, 20, 20) Middle(0, 0, 20, 19);\n");
		form_holder.push_back("                texturethumb = \"icons.png\" Part(143, 154, 20, 20);\n");
		form_holder.push_back("                texturethumbhover = \"icons.png\" Part(143, 174, 20, 20);\n");
		form_holder.push_back("                texturetrack = \"icons.png\" Part(123, 154, 20, 20);\n");
		form_holder.push_back("                texturetrackhover = \"icons.png\" Part(123, 174, 20, 20);\n");
		form_holder.push_back("            }\n");
		form_holder.push_back("        }\n");
		form_holder.push_back("    }\n");
		form_holder.push_back("\n");
		form_holder.push_back("    CheckBox.draw_vector_checkbox {\n");
		form_holder.push_back("        Position = (180, 48);\n");
		form_holder.push_back("        Size = (18, 18);\n");
		form_holder.push_back("        Text = \"Draw Vectors\";\n");
		form_holder.push_back("        TextSize = 10;\n");
		form_holder.push_back("        renderer = &3;\n");
		form_holder.push_back("    }\n");
		form_holder.push_back("}\n");
		form_holder.push_back("\n");
		form_holder.push_back("Tabs.top_tab {\n");
		form_holder.push_back("    AutoSize = 0;\n");
		form_holder.push_back("    Position = (4, 0);\n");
		form_holder.push_back("    Size = (292, 30);\n");
		form_holder.push_back("    Tabs = [Blue/Yellow, Monitor, Manipulate];\n");
		form_holder.push_back("    TextSize = 13;\n");
		form_holder.push_back("    renderer = &4;\n");
		form_holder.push_back("}\n");
		form_holder.push_back("\n");
		form_holder.push_back("Panel.cellSorter_Panel {\n");
		form_holder.push_back("    Position = (4, 280);\n");
		form_holder.push_back("    Size = (292, 560);\n");
		form_holder.push_back("    Visible = false;\n");
		form_holder.push_back("    renderer = &9;\n");
		form_holder.push_back("\n");
		form_holder.push_back("    Picture.cs_BlueSelfPic {\n");
		form_holder.push_back("        Position = (30, 40);\n");
		form_holder.push_back("        Size = (68, 34);\n");
		form_holder.push_back("\n");
		form_holder.push_back("        Renderer {\n");
		form_holder.push_back("            texture = \"icons.png\" Part(0, 209, 128, 64);\n");
		form_holder.push_back("            transparenttexture = true;\n");
		form_holder.push_back("        }\n");
		form_holder.push_back("    }\n");
		form_holder.push_back("\n");
		form_holder.push_back("    Picture.cs_BlueBluePic {\n");
		form_holder.push_back("        Position = (30, 130);\n");
		form_holder.push_back("        Size = (68, 34);\n");
		form_holder.push_back("\n");
		form_holder.push_back("        Renderer {\n");
		form_holder.push_back("            texture = \"icons.png\" Part(0, 273, 128, 64);\n");
		form_holder.push_back("            transparenttexture = true;\n");
		form_holder.push_back("        }\n");
		form_holder.push_back("    }\n");
		form_holder.push_back("\n");
		form_holder.push_back("    Picture.cs_BlueMediumPic {\n");
		form_holder.push_back("        Position = (30, 220);\n");
		form_holder.push_back("        Size = (68, 34);\n");
		form_holder.push_back("\n");
		form_holder.push_back("        Renderer {\n");
		form_holder.push_back("            texture = \"icons.png\" Part(0, 337, 128, 64);\n");
		form_holder.push_back("            transparenttexture = true;\n");
		form_holder.push_back("        }\n");
		form_holder.push_back("    }\n");
		form_holder.push_back("\n");
		form_holder.push_back("    Picture.cs_YellowSelfPic {\n");
		form_holder.push_back("        Position = (180, 40);\n");
		form_holder.push_back("        Size = (68, 34);\n");
		form_holder.push_back("\n");
		form_holder.push_back("        Renderer {\n");
		form_holder.push_back("            texture = \"icons.png\" Part(128, 209, 128, 64);\n");
		form_holder.push_back("            transparenttexture = true;\n");
		form_holder.push_back("        }\n");
		form_holder.push_back("    }\n");
		form_holder.push_back("\n");
		form_holder.push_back("    Picture.cs_YellowYellowfPic {\n");
		form_holder.push_back("        Position = (180, 130);\n");
		form_holder.push_back("        Size = (68, 34);\n");
		form_holder.push_back("\n");
		form_holder.push_back("        Renderer {\n");
		form_holder.push_back("            texture = \"icons.png\" Part(128, 273, 128, 64);\n");
		form_holder.push_back("            transparenttexture = true;\n");
		form_holder.push_back("        }\n");
		form_holder.push_back("    }\n");
		form_holder.push_back("\n");
		form_holder.push_back("    Picture.cs_YellowMediumPic {\n");
		form_holder.push_back("        Position = (180, 220);\n");
		form_holder.push_back("        Size = (68, 34);\n");
		form_holder.push_back("\n");
		form_holder.push_back("        Renderer {\n");
		form_holder.push_back("            texture = \"icons.png\" Part(128, 337, 128, 64);\n");
		form_holder.push_back("            transparenttexture = false;\n");
		form_holder.push_back("        }\n");
		form_holder.push_back("    }\n");
		form_holder.push_back("\n");
		form_holder.push_back("    Picture.cs_BlueYellowPic {\n");
		form_holder.push_back("        Position = (110, 300);\n");
		form_holder.push_back("        Size = (68, 34);\n");
		form_holder.push_back("\n");
		form_holder.push_back("        Renderer {\n");
		form_holder.push_back("            texture = \"icons.png\" Part(0, 401, 128, 64);\n");
		form_holder.push_back("            transparenttexture = true;\n");
		form_holder.push_back("        }\n");
		form_holder.push_back("    }\n");
		form_holder.push_back("\n");
		form_holder.push_back("    Slider.cs_BlueSelf_Slider {\n");
		form_holder.push_back("        ChangeValueOnScroll = true;\n");
		form_holder.push_back("        InvertedDirection = false;\n");
		form_holder.push_back("        Maximum = 50;\n");
		form_holder.push_back("        Minimum = -50;\n");
		form_holder.push_back("        Position = (10, 80);\n");
		form_holder.push_back("        Size = (120, 13);\n");
		form_holder.push_back("        Step = 0.5;\n");
		form_holder.push_back("        Value = -20;\n");
		form_holder.push_back("        renderer = &2;\n");
		form_holder.push_back("    }\n");
		form_holder.push_back("\n");
		form_holder.push_back("    Slider.cs_BlueMedium_Slider {\n");
		form_holder.push_back("        ChangeValueOnScroll = true;\n");
		form_holder.push_back("        InvertedDirection = false;\n");
		form_holder.push_back("        Maximum = 50;\n");
		form_holder.push_back("        Minimum = -50;\n");
		form_holder.push_back("        Position = (10, 260);\n");
		form_holder.push_back("        Size = (120, 13);\n");
		form_holder.push_back("        Step = 0.5;\n");
		form_holder.push_back("        Value = 3;\n");
		form_holder.push_back("        renderer = &2;\n");
		form_holder.push_back("    }\n");
		form_holder.push_back("\n");
		form_holder.push_back("    Slider.cs_BlueBlue_Slider {\n");
		form_holder.push_back("        ChangeValueOnScroll = true;\n");
		form_holder.push_back("        InvertedDirection = false;\n");
		form_holder.push_back("        Maximum = 50;\n");
		form_holder.push_back("        Minimum = -50;\n");
		form_holder.push_back("        Position = (10, 170);\n");
		form_holder.push_back("        Size = (120, 13);\n");
		form_holder.push_back("        Step = 0.5;\n");
		form_holder.push_back("        Value = -6;\n");
		form_holder.push_back("        renderer = &2;\n");
		form_holder.push_back("    }\n");
		form_holder.push_back("\n");
		form_holder.push_back("    Slider.cs_BlueYellow_Slider {\n");
		form_holder.push_back("        ChangeValueOnScroll = true;\n");
		form_holder.push_back("        InvertedDirection = false;\n");
		form_holder.push_back("        Maximum = 50;\n");
		form_holder.push_back("        Minimum = -50;\n");
		form_holder.push_back("        Position = (80, 340);\n");
		form_holder.push_back("        Size = (120, 13);\n");
		form_holder.push_back("        Step = 0.5;\n");
		form_holder.push_back("        Value = 4;\n");
		form_holder.push_back("        renderer = &2;\n");
		form_holder.push_back("    }\n");
		form_holder.push_back("\n");
		form_holder.push_back("    Slider.cs_YellowYellow_Slider {\n");
		form_holder.push_back("        ChangeValueOnScroll = true;\n");
		form_holder.push_back("        InvertedDirection = false;\n");
		form_holder.push_back("        Maximum = 50;\n");
		form_holder.push_back("        Minimum = -50;\n");
		form_holder.push_back("        Position = (150, 170);\n");
		form_holder.push_back("        Size = (120, 13);\n");
		form_holder.push_back("        Step = 0.5;\n");
		form_holder.push_back("        Value = -6;\n");
		form_holder.push_back("        renderer = &2;\n");
		form_holder.push_back("    }\n");
		form_holder.push_back("\n");
		form_holder.push_back("    Slider.cs_YellowSelf_Slider {\n");
		form_holder.push_back("        ChangeValueOnScroll = true;\n");
		form_holder.push_back("        InvertedDirection = false;\n");
		form_holder.push_back("        Maximum = 50;\n");
		form_holder.push_back("        Minimum = -50;\n");
		form_holder.push_back("        Position = (150, 80);\n");
		form_holder.push_back("        Size = (120, 13);\n");
		form_holder.push_back("        Step = 0.5;\n");
		form_holder.push_back("        Value = -20;\n");
		form_holder.push_back("        renderer = &2;\n");
		form_holder.push_back("    }\n");
		form_holder.push_back("\n");
		form_holder.push_back("    Slider.cs_YellowMedium_Slider {\n");
		form_holder.push_back("        ChangeValueOnScroll = true;\n");
		form_holder.push_back("        InvertedDirection = false;\n");
		form_holder.push_back("        Maximum = 50;\n");
		form_holder.push_back("        Minimum = -50;\n");
		form_holder.push_back("        Position = (150, 260);\n");
		form_holder.push_back("        Size = (120, 13);\n");
		form_holder.push_back("        Step = 0.5;\n");
		form_holder.push_back("        Value = 3;\n");
		form_holder.push_back("        renderer = &2;\n");
		form_holder.push_back("    }\n");
		form_holder.push_back("\n");
		form_holder.push_back("    Label.cs_BlueSelf_SliderLabel {\n");
		form_holder.push_back("        HorizontalAlignment = Center;\n");
		form_holder.push_back("        Position = (90, 50);\n");
		form_holder.push_back("        ScrollbarPolicy = Never;\n");
		form_holder.push_back("        Size = (38, 18);\n");
		form_holder.push_back("        TextSize = 12;\n");
		form_holder.push_back("        renderer = &7;\n");
		form_holder.push_back("    }\n");
		form_holder.push_back("\n");
		form_holder.push_back("    Label.cs_BlueMedium_SliderLabel {\n");
		form_holder.push_back("        HorizontalAlignment = Center;\n");
		form_holder.push_back("        Position = (90, 230);\n");
		form_holder.push_back("        ScrollbarPolicy = Never;\n");
		form_holder.push_back("        Size = (38, 18);\n");
		form_holder.push_back("        TextSize = 12;\n");
		form_holder.push_back("        renderer = &7;\n");
		form_holder.push_back("    }\n");
		form_holder.push_back("\n");
		form_holder.push_back("    Label.cs_BlueBlue_SliderLabel {\n");
		form_holder.push_back("        HorizontalAlignment = Center;\n");
		form_holder.push_back("        Position = (90, 140);\n");
		form_holder.push_back("        ScrollbarPolicy = Never;\n");
		form_holder.push_back("        Size = (38, 18);\n");
		form_holder.push_back("        TextSize = 12;\n");
		form_holder.push_back("        renderer = &7;\n");
		form_holder.push_back("    }\n");
		form_holder.push_back("\n");
		form_holder.push_back("    Label.cs_BlueYellow_SliderLabel {\n");
		form_holder.push_back("        HorizontalAlignment = Center;\n");
		form_holder.push_back("        Position = (80, 310);\n");
		form_holder.push_back("        ScrollbarPolicy = Never;\n");
		form_holder.push_back("        Size = (38, 18);\n");
		form_holder.push_back("        TextSize = 12;\n");
		form_holder.push_back("        renderer = &7;\n");
		form_holder.push_back("    }\n");
		form_holder.push_back("\n");
		form_holder.push_back("    Label.cs_YellowYellow_SliderLabel {\n");
		form_holder.push_back("        HorizontalAlignment = Center;\n");
		form_holder.push_back("        Position = (150, 140);\n");
		form_holder.push_back("        ScrollbarPolicy = Never;\n");
		form_holder.push_back("        Size = (38, 18);\n");
		form_holder.push_back("        TextSize = 12;\n");
		form_holder.push_back("        renderer = &7;\n");
		form_holder.push_back("    }\n");
		form_holder.push_back("\n");
		form_holder.push_back("    Label.cs_YellowMedium_SliderLabel {\n");
		form_holder.push_back("        HorizontalAlignment = Center;\n");
		form_holder.push_back("        Position = (150, 230);\n");
		form_holder.push_back("        ScrollbarPolicy = Never;\n");
		form_holder.push_back("        Size = (38, 18);\n");
		form_holder.push_back("        TextSize = 12;\n");
		form_holder.push_back("        renderer = &7;\n");
		form_holder.push_back("    }\n");
		form_holder.push_back("\n");
		form_holder.push_back("    Label.cs_BlueSelf_Label {\n");
		form_holder.push_back("        HorizontalAlignment = Center;\n");
		form_holder.push_back("        Position = (10, 20);\n");
		form_holder.push_back("        ScrollbarPolicy = Never;\n");
		form_holder.push_back("        Size = (107.2, 18);\n");
		form_holder.push_back("        Text = \"Blue - Self\";\n");
		form_holder.push_back("        TextSize = 13;\n");
		form_holder.push_back("        renderer = &7;\n");
		form_holder.push_back("    }\n");
		form_holder.push_back("\n");
		form_holder.push_back("    Label.cs_BlueMedium_Label {\n");
		form_holder.push_back("        HorizontalAlignment = Center;\n");
		form_holder.push_back("        Position = (10, 200);\n");
		form_holder.push_back("        ScrollbarPolicy = Never;\n");
		form_holder.push_back("        Size = (107.2, 18);\n");
		form_holder.push_back("        Text = \"Blue - Medium\";\n");
		form_holder.push_back("        TextSize = 13;\n");
		form_holder.push_back("        renderer = &7;\n");
		form_holder.push_back("    }\n");
		form_holder.push_back("\n");
		form_holder.push_back("    Label.cs_BlueBlue_Label {\n");
		form_holder.push_back("        HorizontalAlignment = Center;\n");
		form_holder.push_back("        Position = (10, 110);\n");
		form_holder.push_back("        ScrollbarPolicy = Never;\n");
		form_holder.push_back("        Size = (107.2, 18);\n");
		form_holder.push_back("        Text = \"Blue - Blue\";\n");
		form_holder.push_back("        TextSize = 13;\n");
		form_holder.push_back("        renderer = &7;\n");
		form_holder.push_back("    }\n");
		form_holder.push_back("\n");
		form_holder.push_back("    Label.cs_BlueYellow_Label {\n");
		form_holder.push_back("        HorizontalAlignment = Center;\n");
		form_holder.push_back("        Position = (90, 280);\n");
		form_holder.push_back("        ScrollbarPolicy = Never;\n");
		form_holder.push_back("        Size = (107.2, 18);\n");
		form_holder.push_back("        Text = \"Blue - Yellow\";\n");
		form_holder.push_back("        TextSize = 13;\n");
		form_holder.push_back("        renderer = &7;\n");
		form_holder.push_back("    }\n");
		form_holder.push_back("\n");
		form_holder.push_back("    Label.cs_YellowYellow_Label {\n");
		form_holder.push_back("        HorizontalAlignment = Center;\n");
		form_holder.push_back("        Position = (160, 110);\n");
		form_holder.push_back("        ScrollbarPolicy = Never;\n");
		form_holder.push_back("        Size = (107.2, 18);\n");
		form_holder.push_back("        Text = \"Yellow - Yellow\";\n");
		form_holder.push_back("        TextSize = 13;\n");
		form_holder.push_back("        renderer = &7;\n");
		form_holder.push_back("    }\n");
		form_holder.push_back("\n");
		form_holder.push_back("    Label.cs_YellowMedium_Label {\n");
		form_holder.push_back("        HorizontalAlignment = Center;\n");
		form_holder.push_back("        Position = (160, 200);\n");
		form_holder.push_back("        ScrollbarPolicy = Never;\n");
		form_holder.push_back("        Size = (107.2, 18);\n");
		form_holder.push_back("        Text = \"Yellow - Medium\";\n");
		form_holder.push_back("        TextSize = 13;\n");
		form_holder.push_back("        renderer = &7;\n");
		form_holder.push_back("    }\n");
		form_holder.push_back("\n");
		form_holder.push_back("    Label.cs_YellowSelf_Label {\n");
		form_holder.push_back("        HorizontalAlignment = Center;\n");
		form_holder.push_back("        Position = (160, 20);\n");
		form_holder.push_back("        ScrollbarPolicy = Never;\n");
		form_holder.push_back("        Size = (107.2, 18);\n");
		form_holder.push_back("        Text = \"Yellow - Self\";\n");
		form_holder.push_back("        TextSize = 13;\n");
		form_holder.push_back("        renderer = &7;\n");
		form_holder.push_back("    }\n");
		form_holder.push_back("\n");
		form_holder.push_back("    Label.cs_YellowSelf_SliderLabel {\n");
		form_holder.push_back("        HorizontalAlignment = Center;\n");
		form_holder.push_back("        Position = (150, 50);\n");
		form_holder.push_back("        ScrollbarPolicy = Never;\n");
		form_holder.push_back("        Size = (38, 18);\n");
		form_holder.push_back("        TextSize = 12;\n");
		form_holder.push_back("        renderer = &7;\n");
		form_holder.push_back("    }\n");
		form_holder.push_back("\n");
		form_holder.push_back("    Picture.cs_blueSizefPic {\n");
		form_holder.push_back("        Position = (50, 360);\n");
		form_holder.push_back("        Size = (54, 54);\n");
		form_holder.push_back("\n");
		form_holder.push_back("        Renderer {\n");
		form_holder.push_back("            texture = \"icons.png\" Part(128, 401, 64, 64);\n");
		form_holder.push_back("            transparenttexture = false;\n");
		form_holder.push_back("        }\n");
		form_holder.push_back("    }\n");
		form_holder.push_back("\n");
		form_holder.push_back("    Picture.cs_yellowSizefPic {\n");
		form_holder.push_back("        Position = (180, 360);\n");
		form_holder.push_back("        Size = (54, 54);\n");
		form_holder.push_back("\n");
		form_holder.push_back("        Renderer {\n");
		form_holder.push_back("            texture = \"icons.png\" Part(192, 401, 64, 64);\n");
		form_holder.push_back("            transparenttexture = false;\n");
		form_holder.push_back("        }\n");
		form_holder.push_back("    }\n");
		form_holder.push_back("\n");
		form_holder.push_back("    Slider.cs_blueSize_slider {\n");
		form_holder.push_back("        ChangeValueOnScroll = true;\n");
		form_holder.push_back("        InvertedDirection = false;\n");
		form_holder.push_back("        Maximum = 500;\n");
		form_holder.push_back("        Minimum = 10;\n");
		form_holder.push_back("        Position = (10, 410);\n");
		form_holder.push_back("        Size = (120, 13);\n");
		form_holder.push_back("        Step = 1;\n");
		form_holder.push_back("        Value = 64;\n");
		form_holder.push_back("        renderer = &2;\n");
		form_holder.push_back("    }\n");
		form_holder.push_back("\n");
		form_holder.push_back("    Slider.cs_yellowSize_slider {\n");
		form_holder.push_back("        ChangeValueOnScroll = true;\n");
		form_holder.push_back("        InvertedDirection = false;\n");
		form_holder.push_back("        Maximum = 500;\n");
		form_holder.push_back("        Minimum = 10;\n");
		form_holder.push_back("        Position = (150, 410);\n");
		form_holder.push_back("        Size = (120, 13);\n");
		form_holder.push_back("        Step = 1;\n");
		form_holder.push_back("        Value = 64;\n");
		form_holder.push_back("        renderer = &2;\n");
		form_holder.push_back("    }\n");
		form_holder.push_back("\n");
		form_holder.push_back("    Label.cs_BlueSize_SliderLabel {\n");
		form_holder.push_back("        HorizontalAlignment = Center;\n");
		form_holder.push_back("        Position = (10, 380);\n");
		form_holder.push_back("        ScrollbarPolicy = Never;\n");
		form_holder.push_back("        Size = (27.2, 18);\n");
		form_holder.push_back("        TextSize = 13;\n");
		form_holder.push_back("        renderer = &7;\n");
		form_holder.push_back("    }\n");
		form_holder.push_back("\n");
		form_holder.push_back("    Label.cs_YellowSize_SliderLabel {\n");
		form_holder.push_back("        HorizontalAlignment = Center;\n");
		form_holder.push_back("        Position = (240, 380);\n");
		form_holder.push_back("        ScrollbarPolicy = Never;\n");
		form_holder.push_back("        Size = (27.2, 18);\n");
		form_holder.push_back("        TextSize = 13;\n");
		form_holder.push_back("        renderer = &7;\n");
		form_holder.push_back("    }\n");
		form_holder.push_back("\n");
		form_holder.push_back("    Slider.cs_colSlider {\n");
		form_holder.push_back("        ChangeValueOnScroll = true;\n");
		form_holder.push_back("        InvertedDirection = false;\n");
		form_holder.push_back("        Maximum = 35;\n");
		form_holder.push_back("        Minimum = 10;\n");
		form_holder.push_back("        Position = (50, 450);\n");
		form_holder.push_back("        Size = (16, 90);\n");
		form_holder.push_back("        Step = 1;\n");
		form_holder.push_back("        Value = 20;\n");
		form_holder.push_back("        renderer = &2;\n");
		form_holder.push_back("    }\n");
		form_holder.push_back("\n");
		form_holder.push_back("    Slider.cs_rowSlider {\n");
		form_holder.push_back("        ChangeValueOnScroll = true;\n");
		form_holder.push_back("        InvertedDirection = false;\n");
		form_holder.push_back("        Maximum = 35;\n");
		form_holder.push_back("        Minimum = 10;\n");
		form_holder.push_back("        Position = (80, 530);\n");
		form_holder.push_back("        Size = (130, 16);\n");
		form_holder.push_back("        Step = 1;\n");
		form_holder.push_back("        Value = 20;\n");
		form_holder.push_back("        renderer = &2;\n");
		form_holder.push_back("    }\n");
		form_holder.push_back("\n");
		form_holder.push_back("    Button.cs_clear_Button {\n");
		form_holder.push_back("        Position = (80, 450);\n");
		form_holder.push_back("        Size = (130, 67.6667);\n");
		form_holder.push_back("        Text = \"Place New Grid\";\n");
		form_holder.push_back("        TextSize = 13;\n");
		form_holder.push_back("        renderer = &8;\n");
		form_holder.push_back("    }\n");
		form_holder.push_back("}\n");
		form_holder.push_back("\n");
		form_holder.push_back("Panel.cellRules_Panel {\n");
		form_holder.push_back("    Position = (4, 280);\n");
		form_holder.push_back("    Size = (292, 480);\n");
		form_holder.push_back("    renderer = &9;\n");
		form_holder.push_back("\n");
		form_holder.push_back("    Label.cr_manualPlacement_label {\n");
		form_holder.push_back("        HorizontalAlignment = Center;\n");
		form_holder.push_back("        Position = (10, 10);\n");
		form_holder.push_back("        ScrollbarPolicy = Never;\n");
		form_holder.push_back("        Size = (267.2, 18.7923);\n");
		form_holder.push_back("        Text = \"Manual Placement\";\n");
		form_holder.push_back("        TextSize = 14;\n");
		form_holder.push_back("        renderer = &7;\n");
		form_holder.push_back("    }\n");
		form_holder.push_back("\n");
		form_holder.push_back("    Label.cr_cell_stateLabel {\n");
		form_holder.push_back("        HorizontalAlignment = Center;\n");
		form_holder.push_back("        IgnoreMouseEvents = true;\n");
		form_holder.push_back("        Position = (10, 30);\n");
		form_holder.push_back("        ScrollbarPolicy = Never;\n");
		form_holder.push_back("        Size = (267.2, 18);\n");
		form_holder.push_back("        Text = \"Cell State\";\n");
		form_holder.push_back("        TextSize = 10;\n");
		form_holder.push_back("        renderer = &7;\n");
		form_holder.push_back("    }\n");
		form_holder.push_back("\n");
		form_holder.push_back("    ComboBox.cr_ManualPlacementComboBox {\n");
		form_holder.push_back("        ChangeItemOnScroll = true;\n");
		form_holder.push_back("        ExpandDirection = Down;\n");
		form_holder.push_back("        ItemsToDisplay = 0;\n");
		form_holder.push_back("        MaximumItems = 0;\n");
		form_holder.push_back("        Position = (63, 44);\n");
		form_holder.push_back("        Size = (160, 28);\n");
		form_holder.push_back("        TextSize = 13;\n");
		form_holder.push_back("\n");
		form_holder.push_back("        Renderer {\n");
		form_holder.push_back("            padding = (3, 3, 3, 3);\n");
		form_holder.push_back("            textcolor = rgb(190, 190, 190);\n");
		form_holder.push_back("            texturearrow = \"icons.png\" Part(60, 0, 32, 32);\n");
		form_holder.push_back("            texturearrowhover = \"icons.png\" Part(60, 32, 32, 32);\n");
		form_holder.push_back("            texturebackground = \"icons.png\" Part(0, 154, 48, 48) Middle(16, 16, 16, 16);\n");
		form_holder.push_back("\n");
		form_holder.push_back("            listbox {\n");
		form_holder.push_back("                backgroundcolorhover = rgb(100, 100, 100);\n");
		form_holder.push_back("                padding = (3, 3, 3, 3);\n");
		form_holder.push_back("                selectedbackgroundcolor = rgb( 10, 110, 255);\n");
		form_holder.push_back("                selectedbackgroundcolorhover = rgb(30, 150, 255);\n");
		form_holder.push_back("                selectedtextcolor = White;\n");
		form_holder.push_back("                textcolor = rgb(190, 190, 190);\n");
		form_holder.push_back("                textcolorhover = rgb(250, 250, 250);\n");
		form_holder.push_back("                texturebackground = \"icons.png\" Part(0, 154, 48, 48) Middle(16, 16, 16, 16);\n");
		form_holder.push_back("\n");
		form_holder.push_back("                scrollbar {\n");
		form_holder.push_back("                    texturearrowdown = \"icons.png\" Part(163, 174, 20, 20) Middle(0, 1, 20, 19);\n");
		form_holder.push_back("                    texturearrowdownhover = \"icons.png\" Part(183, 174, 20, 20) Middle(0, 1, 20, 19);\n");
		form_holder.push_back("                    texturearrowup = \"icons.png\" Part(163, 154, 20, 20) Middle(0, 0, 20, 19);\n");
		form_holder.push_back("                    texturearrowuphover = \"icons.png\" Part(183, 154, 20, 20) Middle(0, 0, 20, 19);\n");
		form_holder.push_back("                    texturethumb = \"icons.png\" Part(143, 154, 20, 20);\n");
		form_holder.push_back("                    texturethumbhover = \"icons.png\" Part(143, 174, 20, 20);\n");
		form_holder.push_back("                    texturetrack = \"icons.png\" Part(123, 154, 20, 20);\n");
		form_holder.push_back("                    texturetrackhover = \"icons.png\" Part(123, 174, 20, 20);\n");
		form_holder.push_back("                }\n");
		form_holder.push_back("            }\n");
		form_holder.push_back("        }\n");
		form_holder.push_back("    }\n");
		form_holder.push_back("\n");
		form_holder.push_back("    CheckBox.cr_manualPlacement_Checkbox {\n");
		form_holder.push_back("        Position = (39, 48);\n");
		form_holder.push_back("        Size = (18, 18);\n");
		form_holder.push_back("        TextSize = 13;\n");
		form_holder.push_back("        renderer = &3;\n");
		form_holder.push_back("    }\n");
		form_holder.push_back("\n");
		form_holder.push_back("    TextBox.monitor_textbox {\n");
		form_holder.push_back("        HorizontalScrollbarPolicy = Never;\n");
		form_holder.push_back("        MaximumCharacters = 0;\n");
		form_holder.push_back("        Position = (7, 120);\n");
		form_holder.push_back("        Size = (278, 325);\n");
		form_holder.push_back("        Text = \"\";\n");
		form_holder.push_back("        TextSize = 9;\n");
		form_holder.push_back("        renderer = &10;\n");
		form_holder.push_back("    }\n");
		form_holder.push_back("\n");
		form_holder.push_back("    Label.cr_press_space_label {\n");
		form_holder.push_back("        HorizontalAlignment = Center;\n");
		form_holder.push_back("        Position = (10, 100);\n");
		form_holder.push_back("        ScrollbarPolicy = Never;\n");
		form_holder.push_back("        Size = (267.2, 18);\n");
		form_holder.push_back("        Text = \"[SPACE to monitor cell under cursor]\";\n");
		form_holder.push_back("        TextSize = 10;\n");
		form_holder.push_back("        renderer = &7;\n");
		form_holder.push_back("    }\n");
		form_holder.push_back("\n");
		form_holder.push_back("    CheckBox._cr_debugcheckbox {\n");
		form_holder.push_back("        Position = (10, 454);\n");
		form_holder.push_back("        Size = (18, 18);\n");
		form_holder.push_back("        Text = \"Debug Monitored Cell\";\n");
		form_holder.push_back("        TextSize = 13;\n");
		form_holder.push_back("        renderer = &3;\n");
		form_holder.push_back("    }\n");
		form_holder.push_back("\n");
		form_holder.push_back("    Label.Label2 {\n");
		form_holder.push_back("        HorizontalAlignment = Center;\n");
		form_holder.push_back("        Position = (10, 74);\n");
		form_holder.push_back("        ScrollbarPolicy = Never;\n");
		form_holder.push_back("        Size = (267.2, 18);\n");
		form_holder.push_back("        Text = \"[ENTER starts new cell]\n\";\n");
		form_holder.push_back("        TextSize = 10;\n");
		form_holder.push_back("        renderer = &7;\n");
		form_holder.push_back("    }\n");
		form_holder.push_back("}\n");
		form_holder.push_back("\n");
		form_holder.push_back("ChildWindow._sd_ChildWindow {\n");
		form_holder.push_back("    Position = (380, 90);\n");
		form_holder.push_back("    Size = (370, 70);\n");
		form_holder.push_back("    Title = \"Save Rules\";\n");
		form_holder.push_back("    TitleAlignment = Center;\n");
		form_holder.push_back("    TitleButtons = Close;\n");
		form_holder.push_back("    renderer = &5;\n");
		form_holder.push_back("\n");
		form_holder.push_back("    EditBox._sd_editBox {\n");
		form_holder.push_back("        Position = (20, 20);\n");
		form_holder.push_back("        Size = (230, 28);\n");
		form_holder.push_back("        TextSize = 13;\n");
		form_holder.push_back("        renderer = &6;\n");
		form_holder.push_back("    }\n");
		form_holder.push_back("\n");
		form_holder.push_back("    Button._sd_saveButton {\n");
		form_holder.push_back("        Position = (270, 20);\n");
		form_holder.push_back("        Size = (77, 20);\n");
		form_holder.push_back("        Text = Save;\n");
		form_holder.push_back("        TextSize = 13;\n");
		form_holder.push_back("        renderer = &8;\n");
		form_holder.push_back("    }\n");
		form_holder.push_back("\n");
		form_holder.push_back("    Label._sd_saveError {\n");
		form_holder.push_back("        HorizontalAlignment = Center;\n");
		form_holder.push_back("        IgnoreMouseEvents = true;\n");
		form_holder.push_back("        Position = (1.39999, 0);\n");
		form_holder.push_back("        ScrollbarPolicy = Never;\n");
		form_holder.push_back("        Size = (367.2, 18);\n");
		form_holder.push_back("        Text = \"*** Error Saving ***\";\n");
		form_holder.push_back("        TextSize = 14;\n");
		form_holder.push_back("        Visible = false;\n");
		form_holder.push_back("        renderer = &7;\n");
		form_holder.push_back("    }\n");
		form_holder.push_back("\n");
		form_holder.push_back("    Label._sd_extension_label {\n");
		form_holder.push_back("        HorizontalAlignment = Center;\n");
		form_holder.push_back("        Position = (0, 50);\n");
		form_holder.push_back("        ScrollbarPolicy = Never;\n");
		form_holder.push_back("        Size = (367.2, 18);\n");
		form_holder.push_back("        Text = \"[Extension .CYR will be automatically added to file name]\";\n");
		form_holder.push_back("        TextSize = 11;\n");
		form_holder.push_back("        renderer = &7;\n");
		form_holder.push_back("    }\n");
		form_holder.push_back("}\n");
		form_holder.push_back("\n");
		form_holder.push_back("ChildWindow._ld_ChildWindow {\n");
		form_holder.push_back("    Position = (380, 280);\n");
		form_holder.push_back("    Size = (400, 280);\n");
		form_holder.push_back("    Title = \"Load Rules\";\n");
		form_holder.push_back("    TitleAlignment = Center;\n");
		form_holder.push_back("    TitleButtons = Close;\n");
		form_holder.push_back("    renderer = &5;\n");
		form_holder.push_back("\n");
		form_holder.push_back("    Label._ld_Label {\n");
		form_holder.push_back("        HorizontalAlignment = Center;\n");
		form_holder.push_back("        IgnoreMouseEvents = true;\n");
		form_holder.push_back("        Position = (30, 210);\n");
		form_holder.push_back("        ScrollbarPolicy = Never;\n");
		form_holder.push_back("        Size = (337.2, 18);\n");
		form_holder.push_back("        Text = \"*** Error Opening File ***\";\n");
		form_holder.push_back("        TextSize = 13;\n");
		form_holder.push_back("        renderer = &7;\n");
		form_holder.push_back("    }\n");
		form_holder.push_back("\n");
		form_holder.push_back("    TextBox._ld_TextBox {\n");
		form_holder.push_back("        HorizontalScrollbarPolicy = Never;\n");
		form_holder.push_back("        MaximumCharacters = 0;\n");
		form_holder.push_back("        Position = (30, 20);\n");
		form_holder.push_back("        ReadOnly = true;\n");
		form_holder.push_back("        Size = (338, 156.528);\n");
		form_holder.push_back("        Text = \"\";\n");
		form_holder.push_back("        TextSize = 13;\n");
		form_holder.push_back("        renderer = &10;\n");
		form_holder.push_back("    }\n");
		form_holder.push_back("\n");
		form_holder.push_back("    EditBox._ld_EditBox {\n");
		form_holder.push_back("        Position = (30, 180);\n");
		form_holder.push_back("        Size = (220, 28);\n");
		form_holder.push_back("        TextSize = 13;\n");
		form_holder.push_back("        renderer = &6;\n");
		form_holder.push_back("    }\n");
		form_holder.push_back("\n");
		form_holder.push_back("    Button._ld_loadButton {\n");
		form_holder.push_back("        Position = (280, 180);\n");
		form_holder.push_back("        Size = (90, 22);\n");
		form_holder.push_back("        Text = Load;\n");
		form_holder.push_back("        TextSize = 13;\n");
		form_holder.push_back("        renderer = &8;\n");
		form_holder.push_back("    }\n");
		form_holder.push_back("\n");
		form_holder.push_back("    Label._ld_Position_File_Error {\n");
		form_holder.push_back("        HorizontalAlignment = Center;\n");
		form_holder.push_back("        Position = (10, 240);\n");
		form_holder.push_back("        ScrollbarPolicy = Never;\n");
		form_holder.push_back("        Size = (367.2, 38);\n");
		form_holder.push_back("        Text = Label;\n");
		form_holder.push_back("        TextSize = 13;\n");
		form_holder.push_back("        renderer = &7;\n");
		form_holder.push_back("    }\n");
		form_holder.push_back("}\n");
		form_holder.push_back("\n");
		form_holder.push_back("ChildWindow._ed_ChildWindow {\n");
		form_holder.push_back("    KeepInParent = true;\n");
		form_holder.push_back("    Position = (348, 50);\n");
		form_holder.push_back("    Resizable = true;\n");
		form_holder.push_back("    Size = (780, 735);\n");
		form_holder.push_back("    Title = \"Rule Editor\";\n");
		form_holder.push_back("    TitleAlignment = Center;\n");
		form_holder.push_back("    TitleButtons = None;\n");
		form_holder.push_back("    renderer = &5;\n");
		form_holder.push_back("\n");
		form_holder.push_back("    TextBox._ed_TextBox {\n");
		form_holder.push_back("        HorizontalScrollbarPolicy = Always;\n");
		form_holder.push_back("        MaximumCharacters = 0;\n");
		form_holder.push_back("        Position = (10, 20);\n");
		form_holder.push_back("        Size = (758, 317.952);\n");
		form_holder.push_back("        Text = \"\";\n");
		form_holder.push_back("        TextSize = 18;\n");
		form_holder.push_back("        renderer = &10;\n");
		form_holder.push_back("    }\n");
		form_holder.push_back("\n");
		form_holder.push_back("    TextBox._ed_errorTextBox {\n");
		form_holder.push_back("        HorizontalScrollbarPolicy = Never;\n");
		form_holder.push_back("        MaximumCharacters = 0;\n");
		form_holder.push_back("        Position = (10, 590);\n");
		form_holder.push_back("        ReadOnly = true;\n");
		form_holder.push_back("        Size = (758, 115);\n");
		form_holder.push_back("        Text = \"\";\n");
		form_holder.push_back("        TextSize = 13;\n");
		form_holder.push_back("\n");
		form_holder.push_back("        Renderer {\n");
		form_holder.push_back("            caretcolor = rgb(110, 110, 255);\n");
		form_holder.push_back("            padding = (3, 3, 3, 3);\n");
		form_holder.push_back("            selectedtextbackgroundcolor = rgb( 10, 110, 255);\n");
		form_holder.push_back("            selectedtextcolor = White;\n");
		form_holder.push_back("            textcolor = rgb(250, 130, 130);\n");
		form_holder.push_back("            texturebackground = \"icons.png\" Part(0, 154, 48, 48) Middle(16, 16, 16, 16);\n");
		form_holder.push_back("\n");
		form_holder.push_back("            scrollbar {\n");
		form_holder.push_back("                texturearrowdown = \"icons.png\" Part(163, 174, 20, 20) Middle(0, 1, 20, 19);\n");
		form_holder.push_back("                texturearrowdownhover = \"icons.png\" Part(183, 174, 20, 20) Middle(0, 1, 20, 19);\n");
		form_holder.push_back("                texturearrowup = \"icons.png\" Part(163, 154, 20, 20) Middle(0, 0, 20, 19);\n");
		form_holder.push_back("                texturearrowuphover = \"icons.png\" Part(183, 154, 20, 20) Middle(0, 0, 20, 19);\n");
		form_holder.push_back("                texturethumb = \"icons.png\" Part(143, 154, 20, 20);\n");
		form_holder.push_back("                texturethumbhover = \"icons.png\" Part(143, 174, 20, 20);\n");
		form_holder.push_back("                texturetrack = \"icons.png\" Part(123, 154, 20, 20);\n");
		form_holder.push_back("                texturetrackhover = \"icons.png\" Part(123, 174, 20, 20);\n");
		form_holder.push_back("            }\n");
		form_holder.push_back("        }\n");
		form_holder.push_back("    }\n");
		form_holder.push_back("\n");
		form_holder.push_back("    Label._ed_filenameLabel {\n");
		form_holder.push_back("        IgnoreMouseEvents = true;\n");
		form_holder.push_back("        Position = (10, 0);\n");
		form_holder.push_back("        ScrollbarPolicy = Never;\n");
		form_holder.push_back("        Size = (447.2, 28);\n");
		form_holder.push_back("        TextSize = 14;\n");
		form_holder.push_back("        renderer = &7;\n");
		form_holder.push_back("    }\n");
		form_holder.push_back("\n");
		form_holder.push_back("    Label._ed_unsaved {\n");
		form_holder.push_back("        HorizontalAlignment = Center;\n");
		form_holder.push_back("        Position = (310, 0);\n");
		form_holder.push_back("        ScrollbarPolicy = Never;\n");
		form_holder.push_back("        Size = (77.2, 18);\n");
		form_holder.push_back("        Text = \"[unsaved]\";\n");
		form_holder.push_back("        TextSize = 13;\n");
		form_holder.push_back("\n");
		form_holder.push_back("        Renderer {\n");
		form_holder.push_back("            textcolor = #FF8C8C;\n");
		form_holder.push_back("            texturebackground = None;\n");
		form_holder.push_back("\n");
		form_holder.push_back("            scrollbar {\n");
		form_holder.push_back("                texturearrowdown = \"icons.png\" Part(163, 174, 20, 20) Middle(0, 1, 20, 19);\n");
		form_holder.push_back("                texturearrowdownhover = \"icons.png\" Part(183, 174, 20, 20) Middle(0, 1, 20, 19);\n");
		form_holder.push_back("                texturearrowup = \"icons.png\" Part(163, 154, 20, 20) Middle(0, 0, 20, 19);\n");
		form_holder.push_back("                texturearrowuphover = \"icons.png\" Part(183, 154, 20, 20) Middle(0, 0, 20, 19);\n");
		form_holder.push_back("                texturethumb = \"icons.png\" Part(143, 154, 20, 20);\n");
		form_holder.push_back("                texturethumbhover = \"icons.png\" Part(143, 174, 20, 20);\n");
		form_holder.push_back("                texturetrack = \"icons.png\" Part(123, 154, 20, 20);\n");
		form_holder.push_back("                texturetrackhover = \"icons.png\" Part(123, 174, 20, 20);\n");
		form_holder.push_back("            }\n");
		form_holder.push_back("        }\n");
		form_holder.push_back("    }\n");
		form_holder.push_back("\n");
		form_holder.push_back("    TextBox._ed_syntaxTextBox {\n");
		form_holder.push_back("        HorizontalScrollbarPolicy = Never;\n");
		form_holder.push_back("        MaximumCharacters = 0;\n");
		form_holder.push_back("        Position = (10, 350);\n");
		form_holder.push_back("        ReadOnly = true;\n");
		form_holder.push_back("        Size = (758, 240);\n");
		form_holder.push_back("        Text = \"\";\n");
		form_holder.push_back("        TextSize = 18;\n");
		form_holder.push_back("\n");
		form_holder.push_back("        Renderer {\n");
		form_holder.push_back("            caretcolor = rgb(110, 110, 255);\n");
		form_holder.push_back("            padding = (3, 3, 3, 3);\n");
		form_holder.push_back("            selectedtextbackgroundcolor = rgb( 10, 110, 255);\n");
		form_holder.push_back("            selectedtextcolor = White;\n");
		form_holder.push_back("            textcolor = #FBFFBF;\n");
		form_holder.push_back("            texturebackground = \"icons.png\" Part(0, 154, 48, 48) Middle(16, 16, 16, 16);\n");
		form_holder.push_back("\n");
		form_holder.push_back("            scrollbar {\n");
		form_holder.push_back("                texturearrowdown = \"icons.png\" Part(163, 174, 20, 20) Middle(0, 1, 20, 19);\n");
		form_holder.push_back("                texturearrowdownhover = \"icons.png\" Part(183, 174, 20, 20) Middle(0, 1, 20, 19);\n");
		form_holder.push_back("                texturearrowup = \"icons.png\" Part(163, 154, 20, 20) Middle(0, 0, 20, 19);\n");
		form_holder.push_back("                texturearrowuphover = \"icons.png\" Part(183, 154, 20, 20) Middle(0, 0, 20, 19);\n");
		form_holder.push_back("                texturethumb = \"icons.png\" Part(143, 154, 20, 20);\n");
		form_holder.push_back("                texturethumbhover = \"icons.png\" Part(143, 174, 20, 20);\n");
		form_holder.push_back("                texturetrack = \"icons.png\" Part(123, 154, 20, 20);\n");
		form_holder.push_back("                texturetrackhover = \"icons.png\" Part(123, 174, 20, 20);\n");
		form_holder.push_back("            }\n");
		form_holder.push_back("        }\n");
		form_holder.push_back("    }\n");
		form_holder.push_back("}\n");
		form_holder.push_back("\n");
		form_holder.push_back("ChildWindow._wts_ChildWindow {\n");
		form_holder.push_back("    Position = (340, 230);\n");
		form_holder.push_back("    Size = (350, 120);\n");
		form_holder.push_back("    TitleAlignment = Center;\n");
		form_holder.push_back("    TitleButtons = None;\n");
		form_holder.push_back("    Visible = false;\n");
		form_holder.push_back("    renderer = &5;\n");
		form_holder.push_back("\n");
		form_holder.push_back("    Button._wts_save_button {\n");
		form_holder.push_back("        Position = (10, 80);\n");
		form_holder.push_back("        Size = (90, 22);\n");
		form_holder.push_back("        Text = Save;\n");
		form_holder.push_back("        TextSize = 13;\n");
		form_holder.push_back("        renderer = &8;\n");
		form_holder.push_back("    }\n");
		form_holder.push_back("\n");
		form_holder.push_back("    Button._wts_discard {\n");
		form_holder.push_back("        Position = (130, 80);\n");
		form_holder.push_back("        Size = (90, 20);\n");
		form_holder.push_back("        Text = Discard;\n");
		form_holder.push_back("        TextSize = 13;\n");
		form_holder.push_back("        renderer = &8;\n");
		form_holder.push_back("    }\n");
		form_holder.push_back("\n");
		form_holder.push_back("    Button._wts_cancel {\n");
		form_holder.push_back("        Position = (250, 80);\n");
		form_holder.push_back("        Size = (90, 22);\n");
		form_holder.push_back("        Text = Cancel;\n");
		form_holder.push_back("        TextSize = 13;\n");
		form_holder.push_back("        renderer = &8;\n");
		form_holder.push_back("    }\n");
		form_holder.push_back("\n");
		form_holder.push_back("    Label._wts_notification {\n");
		form_holder.push_back("        HorizontalAlignment = Center;\n");
		form_holder.push_back("        Position = (0, 40);\n");
		form_holder.push_back("        ScrollbarPolicy = Never;\n");
		form_holder.push_back("        Size = (347.2, 32.1936);\n");
		form_holder.push_back("        Text = \"File has been modified.\nDo you wish to save your changes?\";\n");
		form_holder.push_back("        TextSize = 13;\n");
		form_holder.push_back("        renderer = &7;\n");
		form_holder.push_back("    }\n");
		form_holder.push_back("\n");
		form_holder.push_back("    Label._wts_filename {\n");
		form_holder.push_back("        HorizontalAlignment = Center;\n");
		form_holder.push_back("        Position = (0, 10);\n");
		form_holder.push_back("        ScrollbarPolicy = Never;\n");
		form_holder.push_back("        Size = (347.2, 28);\n");
		form_holder.push_back("        TextSize = 18;\n");
		form_holder.push_back("        renderer = &7;\n");
		form_holder.push_back("    }\n");
		form_holder.push_back("}\n");
		form_holder.push_back("\n");
		form_holder.push_back("Panel.Field_Panel {\n");
		form_holder.push_back("    Position = (4, 60);\n");
		form_holder.push_back("    Size = (292, 500);\n");
		form_holder.push_back("    Visible = false;\n");
		form_holder.push_back("    renderer = &9;\n");
		form_holder.push_back("\n");
		form_holder.push_back("    RadioButton._field_rb_0 {\n");
		form_holder.push_back("        Position = (100, 130);\n");
		form_holder.push_back("        Size = (18, 18);\n");
		form_holder.push_back("        Text = \"Field Value 0\";\n");
		form_holder.push_back("        TextSize = 13;\n");
		form_holder.push_back("        renderer = &1;\n");
		form_holder.push_back("    }\n");
		form_holder.push_back("\n");
		form_holder.push_back("    RadioButton._field_rb_1 {\n");
		form_holder.push_back("        Position = (100, 180);\n");
		form_holder.push_back("        Size = (18, 18);\n");
		form_holder.push_back("        Text = \"Field Value 1\";\n");
		form_holder.push_back("        TextSize = 13;\n");
		form_holder.push_back("        renderer = &1;\n");
		form_holder.push_back("    }\n");
		form_holder.push_back("\n");
		form_holder.push_back("    RadioButton._field_rb_2 {\n");
		form_holder.push_back("        Position = (100, 230);\n");
		form_holder.push_back("        Size = (18, 18);\n");
		form_holder.push_back("        Text = \"Field Value 2\";\n");
		form_holder.push_back("        TextSize = 13;\n");
		form_holder.push_back("        renderer = &1;\n");
		form_holder.push_back("    }\n");
		form_holder.push_back("\n");
		form_holder.push_back("    RadioButton._field_rb_3 {\n");
		form_holder.push_back("        Position = (100, 280);\n");
		form_holder.push_back("        Size = (18, 18);\n");
		form_holder.push_back("        Text = \"Field Value 3\";\n");
		form_holder.push_back("        TextSize = 13;\n");
		form_holder.push_back("        renderer = &1;\n");
		form_holder.push_back("    }\n");
		form_holder.push_back("\n");
		form_holder.push_back("    RadioButton._field_rb_4 {\n");
		form_holder.push_back("        Position = (100, 330);\n");
		form_holder.push_back("        Size = (18, 18);\n");
		form_holder.push_back("        Text = \"Field Value 4\";\n");
		form_holder.push_back("        TextSize = 13;\n");
		form_holder.push_back("        renderer = &1;\n");
		form_holder.push_back("    }\n");
		form_holder.push_back("\n");
		form_holder.push_back("    Picture._field_swatch_0 {\n");
		form_holder.push_back("        IgnoreMouseEvents = true;\n");
		form_holder.push_back("        Position = (30, 120);\n");
		form_holder.push_back("        Size = (44, 44);\n");
		form_holder.push_back("\n");
		form_holder.push_back("        Renderer {\n");
		form_holder.push_back("            texture = \"icons.png\" Part(256, 209, 64, 64);\n");
		form_holder.push_back("            transparenttexture = true;\n");
		form_holder.push_back("        }\n");
		form_holder.push_back("    }\n");
		form_holder.push_back("\n");
		form_holder.push_back("    Picture._field_swatch_1 {\n");
		form_holder.push_back("        IgnoreMouseEvents = true;\n");
		form_holder.push_back("        Position = (30, 170);\n");
		form_holder.push_back("        Size = (44, 44);\n");
		form_holder.push_back("\n");
		form_holder.push_back("        Renderer {\n");
		form_holder.push_back("            texture = \"icons.png\" Part(256, 273, 64, 64);\n");
		form_holder.push_back("            transparenttexture = false;\n");
		form_holder.push_back("        }\n");
		form_holder.push_back("    }\n");
		form_holder.push_back("\n");
		form_holder.push_back("    Picture._field_swatch_2 {\n");
		form_holder.push_back("        Position = (30, 220);\n");
		form_holder.push_back("        Size = (44, 44);\n");
		form_holder.push_back("\n");
		form_holder.push_back("        Renderer {\n");
		form_holder.push_back("            texture = \"icons.png\" Part(256, 337, 64, 64);\n");
		form_holder.push_back("            transparenttexture = false;\n");
		form_holder.push_back("        }\n");
		form_holder.push_back("    }\n");
		form_holder.push_back("\n");
		form_holder.push_back("    Picture._field_swatch_3 {\n");
		form_holder.push_back("        Position = (30, 270);\n");
		form_holder.push_back("        Size = (44, 44);\n");
		form_holder.push_back("\n");
		form_holder.push_back("        Renderer {\n");
		form_holder.push_back("            texture = \"icons.png\" Part(256, 401, 64, 64);\n");
		form_holder.push_back("            transparenttexture = false;\n");
		form_holder.push_back("        }\n");
		form_holder.push_back("    }\n");
		form_holder.push_back("\n");
		form_holder.push_back("    Picture._field_swatch_4 {\n");
		form_holder.push_back("        Position = (30, 320);\n");
		form_holder.push_back("        Size = (44, 44);\n");
		form_holder.push_back("\n");
		form_holder.push_back("        Renderer {\n");
		form_holder.push_back("            texture = \"icons.png\" Part(320, 209, 64, 64);\n");
		form_holder.push_back("            transparenttexture = false;\n");
		form_holder.push_back("        }\n");
		form_holder.push_back("    }\n");
		form_holder.push_back("\n");
		form_holder.push_back("    Slider.field_brushsize {\n");
		form_holder.push_back("        ChangeValueOnScroll = true;\n");
		form_holder.push_back("        InvertedDirection = false;\n");
		form_holder.push_back("        Maximum = 50;\n");
		form_holder.push_back("        Minimum = 5;\n");
		form_holder.push_back("        Position = (30, 390);\n");
		form_holder.push_back("        Size = (230, 16);\n");
		form_holder.push_back("        Step = 1;\n");
		form_holder.push_back("        Value = 5;\n");
		form_holder.push_back("        renderer = &2;\n");
		form_holder.push_back("    }\n");
		form_holder.push_back("\n");
		form_holder.push_back("    Label.field_brushsize_label {\n");
		form_holder.push_back("        HorizontalAlignment = Center;\n");
		form_holder.push_back("        IgnoreMouseEvents = true;\n");
		form_holder.push_back("        Position = (4, 370);\n");
		form_holder.push_back("        ScrollbarPolicy = Never;\n");
		form_holder.push_back("        Size = (277.2, 18);\n");
		form_holder.push_back("        Text = \"Brush Size\";\n");
		form_holder.push_back("        TextSize = 13;\n");
		form_holder.push_back("        renderer = &7;\n");
		form_holder.push_back("    }\n");
		form_holder.push_back("\n");
		form_holder.push_back("    Button.field_save {\n");
		form_holder.push_back("        Position = (170, 20);\n");
		form_holder.push_back("        Size = (108, 30);\n");
		form_holder.push_back("        Text = \"Save Field\";\n");
		form_holder.push_back("        TextSize = 13;\n");
		form_holder.push_back("        renderer = &8;\n");
		form_holder.push_back("    }\n");
		form_holder.push_back("\n");
		form_holder.push_back("    Button.field_load {\n");
		form_holder.push_back("        Position = (10, 20);\n");
		form_holder.push_back("        Size = (108, 30);\n");
		form_holder.push_back("        Text = \"Load Field\";\n");
		form_holder.push_back("        TextSize = 13;\n");
		form_holder.push_back("        renderer = &8;\n");
		form_holder.push_back("    }\n");
		form_holder.push_back("\n");
		form_holder.push_back("    Button.field_clear {\n");
		form_holder.push_back("        Position = (170, 60);\n");
		form_holder.push_back("        Size = (108, 30);\n");
		form_holder.push_back("        Text = \"Clear Field\";\n");
		form_holder.push_back("        TextSize = 13;\n");
		form_holder.push_back("        renderer = &8;\n");
		form_holder.push_back("    }\n");
		form_holder.push_back("\n");
		form_holder.push_back("    CheckBox._ft_Adjust_Checkbox {\n");
		form_holder.push_back("        Position = (30, 420);\n");
		form_holder.push_back("        Size = (18, 18);\n");
		form_holder.push_back("        Text = \"   Adjust Default Presumed Location\";\n");
		form_holder.push_back("        TextSize = 10;\n");
		form_holder.push_back("        renderer = &3;\n");
		form_holder.push_back("    }\n");
		form_holder.push_back("\n");
		form_holder.push_back("    Knob.field_knob {\n");
		form_holder.push_back("        ClockwiseTurning = true;\n");
		form_holder.push_back("        EndRotation = 90;\n");
		form_holder.push_back("        Maximum = 360;\n");
		form_holder.push_back("        Minimum = 0;\n");
		form_holder.push_back("        Position = (20, 445);\n");
		form_holder.push_back("        Size = (40, 40);\n");
		form_holder.push_back("        StartRotation = 90;\n");
		form_holder.push_back("        Value = 0;\n");
		form_holder.push_back("\n");
		form_holder.push_back("        Renderer {\n");
		form_holder.push_back("            imagerotation = 90;\n");
		form_holder.push_back("            texturebackground = none;\n");
		form_holder.push_back("            textureforeground = none;\n");
		form_holder.push_back("        }\n");
		form_holder.push_back("    }\n");
		form_holder.push_back("\n");
		form_holder.push_back("    Label.knob_label {\n");
		form_holder.push_back("        Position = (63, 460);\n");
		form_holder.push_back("        ScrollbarPolicy = Never;\n");
		form_holder.push_back("        Size = (207.2, 18);\n");
		form_holder.push_back("        Text = \"Adjust Default Presumed Orientation\";\n");
		form_holder.push_back("        TextSize = 10;\n");
		form_holder.push_back("        renderer = &7;\n");
		form_holder.push_back("    }\n");
		form_holder.push_back("\n");
		form_holder.push_back("    Label.knob_value_label {\n");
		form_holder.push_back("        HorizontalAlignment = Center;\n");
		form_holder.push_back("        Position = (70, 470);\n");
		form_holder.push_back("        ScrollbarPolicy = Never;\n");
		form_holder.push_back("        Size = (147.2, 18);\n");
		form_holder.push_back("        Text = 0;\n");
		form_holder.push_back("        TextSize = 13;\n");
		form_holder.push_back("        renderer = &7;\n");
		form_holder.push_back("    }\n");
		form_holder.push_back("}\n");
		form_holder.push_back("\n");
		form_holder.push_back("Panel.manipulate_panel {\n");
		form_holder.push_back("    Position = (4, 60);\n");
		form_holder.push_back("    Size = (292, 220);\n");
		form_holder.push_back("    Visible = false;\n");
		form_holder.push_back("    renderer = &9;\n");
		form_holder.push_back("\n");
		form_holder.push_back("    RadioButton.manipu_rb_select {\n");
		form_holder.push_back("        Position = (90, 40);\n");
		form_holder.push_back("        Size = (28, 28);\n");
		form_holder.push_back("        Text = Select;\n");
		form_holder.push_back("        TextSize = 12;\n");
		form_holder.push_back("        renderer = &1;\n");
		form_holder.push_back("    }\n");
		form_holder.push_back("\n");
		form_holder.push_back("    RadioButton.manipu_rb_deselect {\n");
		form_holder.push_back("        Position = (90, 80);\n");
		form_holder.push_back("        Size = (28, 28);\n");
		form_holder.push_back("        Text = Deselect;\n");
		form_holder.push_back("        TextSize = 12;\n");
		form_holder.push_back("        renderer = &1;\n");
		form_holder.push_back("    }\n");
		form_holder.push_back("\n");
		form_holder.push_back("    RadioButton.manipu_rb_move {\n");
		form_holder.push_back("        Position = (90, 120);\n");
		form_holder.push_back("        Size = (28, 28);\n");
		form_holder.push_back("        Text = \"Move Selected Cells\";\n");
		form_holder.push_back("        TextSize = 12;\n");
		form_holder.push_back("        renderer = &1;\n");
		form_holder.push_back("    }\n");
		form_holder.push_back("\n");
		form_holder.push_back("    Button.manip_kill {\n");
		form_holder.push_back("        Position = (70, 170);\n");
		form_holder.push_back("        Size = (138, 26);\n");
		form_holder.push_back("        Text = \"Kill Selected Cells\";\n");
		form_holder.push_back("        TextSize = 13;\n");
		form_holder.push_back("        renderer = &8;\n");
		form_holder.push_back("    }\n");
		form_holder.push_back("}\n");
		form_holder.push_back("\n");
		form_holder.push_back("Tabs.bottom_tab {\n");
		form_holder.push_back("    AutoSize = 0;\n");
		form_holder.push_back("    Position = (4, 30);\n");
		form_holder.push_back("    Size = (292, 30);\n");
		form_holder.push_back("    Tabs = [\"Field Editor\", \"Rule Editor\"];\n");
		form_holder.push_back("    TextSize = 13;\n");
		form_holder.push_back("    renderer = &4;\n");
		form_holder.push_back("}\n");
		form_holder.push_back("\n");
		form_holder.push_back("Panel.Editor_Panel {\n");
		form_holder.push_back("    Position = (4, 60);\n");
		form_holder.push_back("    Size = (292, 750);\n");
		form_holder.push_back("    renderer = &9;\n");
		form_holder.push_back("\n");
		form_holder.push_back("    Button.compile_rules {\n");
		form_holder.push_back("        Position = (90, 60);\n");
		form_holder.push_back("        Size = (108, 30);\n");
		form_holder.push_back("        Text = \"Compile Rules\";\n");
		form_holder.push_back("        TextSize = 13;\n");
		form_holder.push_back("        renderer = &8;\n");
		form_holder.push_back("    }\n");
		form_holder.push_back("\n");
		form_holder.push_back("    Button.save_rules {\n");
		form_holder.push_back("        Position = (170, 20);\n");
		form_holder.push_back("        Size = (108, 30);\n");
		form_holder.push_back("        Text = \"Save Rules\";\n");
		form_holder.push_back("        TextSize = 13;\n");
		form_holder.push_back("        renderer = &8;\n");
		form_holder.push_back("    }\n");
		form_holder.push_back("\n");
		form_holder.push_back("    Button.load_rules {\n");
		form_holder.push_back("        Position = (10, 20);\n");
		form_holder.push_back("        Size = (108, 30);\n");
		form_holder.push_back("        Text = \"Load Rules\";\n");
		form_holder.push_back("        TextSize = 13;\n");
		form_holder.push_back("        renderer = &8;\n");
		form_holder.push_back("    }\n");
		form_holder.push_back("\n");
		form_holder.push_back("    Button.syntax_guide_button {\n");
		form_holder.push_back("        Position = (90, 230);\n");
		form_holder.push_back("        Size = (108, 30);\n");
		form_holder.push_back("        Text = \"Syntax Guide\";\n");
		form_holder.push_back("        TextSize = 13;\n");
		form_holder.push_back("        renderer = &8;\n");
		form_holder.push_back("    }\n");
		form_holder.push_back("}\n");
		form_holder.push_back("\n");
		form_holder.push_back("TextBox._debug_textbox {\n");
		form_holder.push_back("    HorizontalScrollbarPolicy = Never;\n");
		form_holder.push_back("    MaximumCharacters = 0;\n");
		form_holder.push_back("    Position = (434, 660);\n");
		form_holder.push_back("    ReadOnly = true;\n");
		form_holder.push_back("    Size = (608, 155);\n");
		form_holder.push_back("    Text = \"\";\n");
		form_holder.push_back("    TextSize = 10;\n");
		form_holder.push_back("    Visible = false;\n");
		form_holder.push_back("\n");
		form_holder.push_back("    Renderer {\n");
		form_holder.push_back("        caretcolor = rgb(110, 110, 255);\n");
		form_holder.push_back("        padding = (3, 3, 3, 3);\n");
		form_holder.push_back("        selectedtextbackgroundcolor = rgb( 10, 110, 255);\n");
		form_holder.push_back("        selectedtextcolor = White;\n");
		form_holder.push_back("        textcolor = rgb(190, 190, 190);\n");
		form_holder.push_back("        texturebackground = \"icons.png\" Part(0, 154, 48, 48) Middle(16, 16, 16, 16);\n");
		form_holder.push_back("\n");
		form_holder.push_back("        scrollbar {\n");
		form_holder.push_back("            texturearrowdown = \"icons.png\" Part(163, 174, 20, 20) Middle(0, 1, 20, 19);\n");
		form_holder.push_back("            texturearrowdownhover = \"icons.png\" Part(183, 174, 20, 20) Middle(0, 1, 20, 19);\n");
		form_holder.push_back("            texturearrowup = \"icons.png\" Part(163, 154, 20, 20) Middle(0, 0, 20, 19);\n");
		form_holder.push_back("            texturearrowuphover = \"icons.png\" Part(183, 154, 20, 20) Middle(0, 0, 20, 19);\n");
		form_holder.push_back("            texturethumb = \"icons.png\" Part(143, 154, 20, 20);\n");
		form_holder.push_back("            texturethumbhover = \"icons.png\" Part(143, 174, 20, 20);\n");
		form_holder.push_back("            texturetrack = \"icons.png\" Part(123, 154, 20, 20);\n");
		form_holder.push_back("            texturetrackhover = \"icons.png\" Part(123, 174, 20, 20);\n");
		form_holder.push_back("        }\n");
		form_holder.push_back("    }\n");
		form_holder.push_back("}\n");
		form_holder.push_back("\n");
		form_holder.push_back("TextBox.rule_viewer {\n");
		form_holder.push_back("    HorizontalScrollbarPolicy = Never;\n");
		form_holder.push_back("    MaximumCharacters = 0;\n");
		form_holder.push_back("    Position = (430, 420);\n");
		form_holder.push_back("    ReadOnly = true;\n");
		form_holder.push_back("    Size = (598, 215);\n");
		form_holder.push_back("    Text = \"\";\n");
		form_holder.push_back("    TextSize = 10;\n");
		form_holder.push_back("    Visible = false;\n");
		form_holder.push_back("\n");
		form_holder.push_back("    Renderer {\n");
		form_holder.push_back("        caretcolor = rgb(110, 110, 255);\n");
		form_holder.push_back("        padding = (3, 3, 3, 3);\n");
		form_holder.push_back("        selectedtextbackgroundcolor = rgb( 10, 110, 255);\n");
		form_holder.push_back("        selectedtextcolor = White;\n");
		form_holder.push_back("        textcolor = #F7FFAB;\n");
		form_holder.push_back("        texturebackground = \"icons.png\" Part(0, 154, 48, 48) Middle(16, 16, 16, 16);\n");
		form_holder.push_back("\n");
		form_holder.push_back("        scrollbar {\n");
		form_holder.push_back("            texturearrowdown = \"icons.png\" Part(163, 174, 20, 20) Middle(0, 1, 20, 19);\n");
		form_holder.push_back("            texturearrowdownhover = \"icons.png\" Part(183, 174, 20, 20) Middle(0, 1, 20, 19);\n");
		form_holder.push_back("            texturearrowup = \"icons.png\" Part(163, 154, 20, 20) Middle(0, 0, 20, 19);\n");
		form_holder.push_back("            texturearrowuphover = \"icons.png\" Part(183, 154, 20, 20) Middle(0, 0, 20, 19);\n");
		form_holder.push_back("            texturethumb = \"icons.png\" Part(143, 154, 20, 20);\n");
		form_holder.push_back("            texturethumbhover = \"icons.png\" Part(143, 174, 20, 20);\n");
		form_holder.push_back("            texturetrack = \"icons.png\" Part(123, 154, 20, 20);\n");
		form_holder.push_back("            texturetrackhover = \"icons.png\" Part(123, 174, 20, 20);\n");
		form_holder.push_back("        }\n");
		form_holder.push_back("    }\n");
		form_holder.push_back("}\n");
		form_holder.push_back("\n");
	
	
	

		for (int x = 0; x < form_holder.size(); x++) {
			form_file << form_holder[x];
		}
	}
};

